use std::io;
fn main() {
let mut Exit = String::new();
//Exit = "";

println!("J. R. R. Tolkien - Zoti i unazave.");
println!("Një nga katër");
println!("-----------------------------------------------");
println!("ZOTI I unazave");
println!("nga");
println!("J. R. R. TOLKIEN");
println!("Pjesa e Parë: Shoqëria e Unazës");
println!("Pjesa e Dytë: Dy Kullat");
println!("Pjesa e tretë: Kthimi i mbretit");
println!("E plotësuar me indeks dhe shtojca të plota");
println!("Tre unaza për mbretërit Elven nën qiell");
println!("Shtatë për zotërinjtë xhuxh në sallat e tyre prej guri");
println!("Nëntë për burrat e vdekshëm të dënuar të vdesin,");
println!("Një për Zotin e Errët në fronin e tij të errët");
println!("Në Tokën e Mordorit ku shtrihen Hijet.");
println!("Një unazë për t'i sunduar të gjithë,");
println!("Një unazë për t'i gjetur");
println!("Një Unazë për t'i sjellë të gjitha dhe në errësirë t'i lidhë");
println!("Në Tokën e Mordorit ku shtrihen Hijet.");
println!("PERMBAJTJA");
println!("PARATHËNIE");
println!("PROLOG");
println!("1. Në lidhje me Hobbitët");
println!("2. Lidhur me gypat e barërave të këqija");
println!("3. E Rendit te Shire");
println!("4. Nga Gjetja e Unazës");
println!("Shënim mbi të dhënat Shire");
println!("SHOQËRIA E UNAZËS");
println!("Libri i parë:");
println!("Kapitulli 1 Një festë e pritur prej kohësh");
println!("Kapitulli 2 Hija e së kaluarës");
println!("Kapitulli 3 është kompani");
println!("Kapitulli 4 Një prerje e shkurtër për kërpudhat");
println!("Kapitulli 5 Një komplot i demaskuar");
println!("Kapitulli 6 Pylli i Vjetër");
println!("Kapitulli 7 Në shtëpinë e Tom Bombadil");
println!("Kapitulli 8 Mjegulla në Barrow-Downs");
println!("Kapitulli 9 Në shenjën e kalit të vogël");
println!("Kapitulli 10 Strider");
println!("Kapitulli 11 Një thikë në errësirë");
println!("Kapitulli 12 Fluturimi për në Ford");
println!("Libri i dyte:");
println!("Kapitulli 1 Shumë Takime");
println!("Kapitulli 2 Këshilli i Elrondit");
println!("Kapitulli 3 Unaza shkon në jug");
println!("Kapitulli 4 Një udhëtim në errësirë");
println!("Kapitulli 5 Ura e Khazad-dûm");
println!("Kapitulli 6 Lothlórien");
println!("Kapitulli 7 Pasqyra e Galadrielit");
println!("Kapitulli 8 Lamtumire Lórien");
println!("Kapitulli 9 Lumi i Madh");
println!("Kapitulli 10 Thyerja e Bashkësisë");
println!("DY KULLAT");
println!("Libri Tre:");
println!("Kapitulli 1 Largimi i Boromir");
println!("Kapitulli 2 Kalorësit e Rohanit");
println!("Kapitulli 3 Uruk-Hai");
println!("Kapitulli 4 Mjekër Pema");
println!("Kapitulli 5 Kalorësi i Bardhë");
println!("Kapitulli 6 Mbreti i Sallës së Artë");
println!("Kapitulli 7 Helm's Deep");
println!("Kapitulli 8 Rruga drejt Isengardit");
println!("Kapitulli 9 Flotsam dhe Jetsam");
println!("Kapitulli 10 Zëri i Sarumanit");
println!("Kapitulli 11 Palantir");
println!("Libri i katërt:");
println!("Kapitulli 1 Zbutja e Sméagol");
println!("Kapitulli 2 Kalimi i kënetave");
println!("Kapitulli 3 Porta e Zezë është e Mbyllur");
println!("Kapitulli 4 i barishteve dhe lepurit të zier");
println!("Kapitulli 5 Dritarja në Perëndim");
println!("Kapitulli 6 Pishina e Ndaluar");
println!("Kapitulli 7 Udhëtim në udhëkryq");
println!("Kapitulli 8 Shkallët e Cirith Ungol");
println!("Kapitulli 9 Varri i Shelobit");
println!("Kapitulli 10 Zgjedhjet e Master Samwise");
println!("KTHIMI I MBRETIT");
println!("Libri i peste:");
println!("Kapitulli 1 Minas Tirith");
println!("Kapitulli 2 Kalimi i Kompanisë Gri");
println!("Kapitulli 3 The Monster of Rohan");
println!("Kapitulli 4 Rrethimi i Gondorit");
println!("Kapitulli 5 Udhëtimi i Rohirrim");
println!("Kapitulli 6 Beteja e Fushave Pelennor");
println!("Kapitulli 7 Pyre of Denethor");
println!("Kapitulli 8 Shtëpitë e Shërimit");
println!("Kapitulli 9 Debati i fundit");
println!("Kapitulli 10 Hapet Porta e Zezë");
println!("Libri i Gjashtë:");
println!("Kapitulli 1 Kulla e Cirith Ungol");
println!("Kapitulli 2 Toka e hijes");
println!("Kapitulli 3 Mount Doom");
println!("Kapitulli 4 Fusha e Cormallen");
println!("Kapitulli 5 Kujdestari dhe Mbreti");
println!("Kapitulli 6 Shumë ndarje");
println!("Kapitulli 7 Lidhur në shtëpi");
println!("Kapitulli 8 Pastrimi i Shirit");
println!("Kapitulli 9 The Grey Havens");
println!("SHTOJCA");
println!("NJË ANALI I MBRETIT DHE Sundimtarëve");
println!("Unë Mbretërit Numenorean");
println!("(I) Númenor");
println!("(II) Mbretëritë në mërgim");
println!("(III) Eriador, Arnor dhe Trashëgimtarët e Isildurit");
println!("(IV) Gondor dhe trashëgimtarët e Anñrion");
println!("(V) Këtu vijon një pjesë e Përrallës së Aragorn dhe Arwen");
println!("II THE HOUSE OF EORL");
println!("FOLKRI I III DURINIT");
println!("Këtu vijon një nga shënimet e fundit në Librin e Kuq");
println!("B PERRALLA E VITIT (KRONOLOGJIA E VENDEVE PERENDIMORE)");
println!("Epoka e Dyte");
println!("Epoka e Trete");
println!("PEMËT FAMILJARE C");
println!("KALENDARET D");
println!("KALENDAR SHIRE PËR PËRDORIM NË TË GJITHA VITET");
println!("KALENDARET");
println!("SHKRIMI DHE DREJTSHKRIMI");
println!("I shqiptimi i fjaleve dhe i emrave");
println!("Shkrimi II");
println!("F");
println!("Unë gjuhët dhe popujt e epokës së tretë");
println!("II Mbi Përkthimin");
println!("INDEKSET");
println!("I Këngë dhe Vargje");
println!("II Persona, Bisha dhe Përbindësha");
println!("Vendet III");
println!("IV Gjërat");
println!("----------------------------------------------");
println!("PARATHËNIE");
println!("Kjo përrallë u rrit në tregim, derisa u bë histori e Luftës së Madhe të Unazës dhe përfshiu shumë pamje të historisë akoma më të lashtë që i parapriu.");
println!("Ai filloi menjëherë pasi u shkrua 'Hobbit' dhe para botimit të tij në 1937;");
println!("por nuk vazhdova me këtë vazhdim, sepse doja së pari të plotësoja dhe të rregulloja mitologjinë dhe legjendat e Ditëve të Pleqve, që atëherë kishin marrë formë prej disa vitesh.");
println!("Dëshiroja ta bëja këtë për kënaqësinë time dhe kisha pak shpresë se njerëzit e tjerë do të ishin të interesuar për këtë punë,");
println!("veçanërisht pasi ishte kryesisht gjuhësor në frymëzim dhe filloi për të siguruar sfondin e nevojshëm të 'historisë' për gjuhët elvish.");
println!("Kur ata, këshillat dhe mendimet e të cilëve kërkova, korrigjuan pak shpresë në pa shpresë, u ktheva në vazhdim");
println!("inkurajuar nga kërkesat e lexuesve për më shumë informacion në lidhje me hobbitët dhe aventurat e tyre.");
println!("Por historia u tërhoq në mënyrë të papërmbajtshme drejt botës së vjetër dhe u bë një rrëfim, si të thuash, i fundit dhe i vdekjes së saj para se të tregohej fillimi dhe mesi i saj.");
println!("Procesi kishte filluar në shkrimin e The Hobbit, në të cilin tashmë kishte disa referenca për çështjen më të vjetër:");
println!("Elrond, Gondolin, High-Elf-të dhe orkët, si dhe pamjet që kishin dalë pa u shfaqur nga gjërat më të larta ose më të thella ose më të errëta se sipërfaqja e tij:");
println!("Durin, Moria, Gandalf, Necromancer, Unaza.");
println!("Zbulimi i rëndësisë së këtyre pamjeve dhe i lidhjes së tyre me historitë e lashta zbuloi Epokën e Tretë dhe kulmin e saj në Luftën e Unazës.");
println!("Ata që kishin kërkuar më shumë informacion për hobbitët më në fund e morën atë, por u duhej të prisnin shumë;");
println!("sepse kompozimi i 'The Lord of the Rings' vazhdoi me intervale gjatë viteve 1936 deri në 1949,");
println!("një periudhë në të cilën kisha shumë detyra që nuk i lashë pas dore dhe shumë interesa të tjera si nxënës dhe mësues që shpesh më përthithën.");
println!("Vonesat, natyrisht, u rritën edhe nga shpërthimi i luftës në vitin 1939, në fund të të cilit përralla nuk kishte arritur ende në fund të Librit të Parë.");
println!("Megjithë errësirën e pesë viteve të ardhshme, kuptova se historia tani nuk mund të braktisej plotësisht, dhe vazhdova, kryesisht natën, derisa qëndrova pranë varrit të Balinit në Moria.");
println!("Atje ndalova për një kohë të gjatë.");
println!("Ishte pothuajse një vit më vonë kur vazhdova dhe kështu erdha në Lothlórien dhe në lumin e Madh në fund të 1941.");
println!("Në vitin e ardhshëm shkrova draftet e para të çështjes që tani qëndron si Libri i Tretë,");
println!("dhe fillimet e kapitujve I dhe III te librit pese;");
println!("dhe aty teksa fenerët u ndezën në Anórien dhe Théoden erdhën në Harrowdale, unë ndalova.");
println!("Parashikimi kishte dështuar dhe nuk kishte kohë për të menduar.");
println!("Ka qenë gjatë vitit 1944 që, duke lënë përfundimet e lira dhe hutimet e një lufte që ishte detyra ime ta drejtoja, ose të paktën të raportoja, e detyrova veten të merrem me udhëtimin e Frodos në Mordor.");
println!("Këta kapituj, që përfundimisht do të bëhen Libri i Katërt, u shkruan dhe iu dërguan si serial djalit tim, Christopher, atëherë në Afrikën e Jugut me RAF.");
println!("Megjithatë u deshën edhe pesë vjet para se përralla të arrinte në fundin e saj aktual;");
println!("në atë kohë unë ndryshova shtëpinë time, karrigen time dhe kolegjin tim, dhe ditët edhe pse më pak të errëta nuk ishin më pak të mundimshme.");
println!("Atëherë kur më në fund u arrit 'fundi', e gjithë historia duhej të rishikohej dhe në të vërtetë të rishkruhej në masë të madhe mbrapsht.");
println!("Dhe duhej të shtypej dhe të rishkruhej:");
println!("nga unë;");
println!("kostoja e shtypjes profesionale me dhjetë gishta ishte përtej mundësive të mia.");
println!("Zoti i unazave është lexuar nga shumë njerëz që kur u shfaq më në fund në shtyp;");
println!("dhe unë do të doja të them diçka këtu duke iu referuar shumë mendimeve ose supozimeve që kam marrë ose kam lexuar në lidhje me motivet dhe kuptimin e përrallës.");
println!("Motivi kryesor ishte dëshira e një tregimtari për të provuar dorën e tij në një histori vërtet të gjatë që do të tërhiqte vëmendjen e lexuesve");
println!("zbavitini, kënaqini dhe ndonjëherë mund t'i ngacmoni ose t'i prekni thellë.");
println!("Si udhërrëfyes unë kisha vetëm ndjenjat e mia për atë që është tërheqëse ose lëvizëse, dhe për shumë njerëz udhërrëfyesi ishte në mënyrë të pashmangshme shpesh në faj.");
println!("Disa që e kanë lexuar librin, ose në çdo rast e kanë rishikuar, e kanë parë të mërzitshëm, absurd ose të përçmuar;");
println!("dhe nuk kam pse të ankohem, pasi kam mendime të ngjashme për veprat e tyre, ose për llojet e shkrimeve që ata me sa duket preferojnë.");
println!("Por edhe nga këndvështrimi i shumë atyre që e kanë shijuar historinë time ka shumë gjëra që nuk mund të kënaqin.");
println!("Ndoshta nuk është e mundur në një përrallë të gjatë t'i kënaqësh të gjithë në të gjitha pikat, as të mos i kënaqësh të gjithë në të njëjtat pika;");
println!("sepse nga letrat që kam marrë zbuloj se pasazhet ose kapitujt që janë për disa të meta janë të gjitha të miratuara posaçërisht nga të tjerët.");
println!("Lexuesi më kritik nga të gjithë, unë, tani gjen shumë defekte, të vogla dhe të mëdha,");
println!("por fatmirësisht duke mos pasur asnjë detyrim as ta rishikojë librin, as ta shkruajë përsëri, ai do t'i kalojë këto në heshtje,");
println!("përveç një që është shënuar nga të tjerët:");
println!("libri është shumë i shkurtër.");
println!("Sa i përket çdo kuptimi ose 'mesazhi' të brendshëm, ai nuk ka në qëllimin e autorit asnjë.");
println!("Nuk eshte as alegorike dhe as aktuale.");
println!("Ndërsa historia u rrit, ajo hodhi rrënjët (në të kaluarën) dhe hodhi degë të papritura:");
println!("por tema e saj kryesore u zgjidh që në fillim nga zgjedhja e pashmangshme e Unazës si lidhje midis saj dhe Hobbit.");
println!("Kapitulli vendimtar 'Hija e së kaluarës', është një nga pjesët më të vjetra të përrallës.");
println!("U shkrua shumë kohë përpara se parathënia e vitit 1939 të ishte bërë ende një kërcënim i fatkeqësisë së pashmangshme");
println!("dhe nga ajo pikë historia do të ishte zhvilluar në thelb në të njëjtat linja, nëse ajo fatkeqësi do të ishte shmangur.");
println!("Burimet e tij janë gjëra shumë më parë në mendje, ose në disa raste tashmë të shkruara,");
println!("dhe pak ose aspak në të u modifikua nga lufta që filloi në 1939 ose nga vazhdimet e saj.");
println!("Lufta e vërtetë nuk i ngjan luftës legjendare në procesin e saj apo përfundimin e saj.");
println!("Nëse do të kishte frymëzuar ose drejtuar zhvillimin e legjendës, atëherë me siguri Unaza do të ishte kapur dhe përdorur kundër Sauronit;");
println!("ai nuk do të ishte asgjësuar, por robëruar, dhe Barad-dûr nuk do të ishte shkatërruar, por pushtuar.");
println!("Saruman, duke dështuar për të zotëruar Unazën,");
println!("a do të kishte gjetur në konfuzionin dhe tradhtitë e kohës tek Mordor hallkat që mungojnë në kërkimet e tij në Ring-lore,");
println!("dhe pa kaluar shumë kohë ai do të kishte bërë një Unazë të Madhe të tijën me të cilën do të sfidonte Sundimtarin e vetëquajtur të Tokës së Mesme.");
println!("Në atë konflikt të dyja palët do t'i kishin mbajtur hobbit në urrejtje dhe përbuzje:");
println!("ata nuk do të kishin mbijetuar gjatë edhe si skllevër.");
println!("Aranzhime të tjera mund të krijohen sipas shijeve ose pikëpamjeve të atyre që pëlqejnë alegorinë ose referencën aktuale.");
println!("Por mua nuk më pëlqen përzemërsisht alegoria në të gjitha manifestimet e saj, dhe gjithmonë e kam bërë këtë që kur jam plakur dhe mjaft i kujdesshëm për të zbuluar praninë e saj.");
println!("Unë e preferoj shumë historinë, të vërtetë apo të shtirur, me zbatueshmërinë e saj të larmishme në mendimin dhe përvojën e lexuesve.");
println!("Unë mendoj se shumë ngatërrojnë 'zbatueshmërinë' me 'alegorinë';");
println!("por njëra qëndron në lirinë e lexuesit dhe tjetra në dominimin e synuar të autorit.");
println!("Një autor sigurisht që nuk mund të mbetet tërësisht i pandikuar nga përvoja e tij,");
println!("por mënyrat në të cilat një mikrob histori përdor tokën e përvojës janë jashtëzakonisht komplekse,");
println!("dhe përpjekjet për të përcaktuar procesin janë supozime më të mira nga provat që janë të pamjaftueshme dhe të paqarta.");
println!("Është gjithashtu e rreme, ndonëse natyrshëm tërheqëse, kur jeta e një autori dhe kritiku janë mbivendosur");
println!("të supozojmë se lëvizjet e mendimit ose ngjarjet e kohërave të përbashkëta për të dyja ishin domosdoshmërisht ndikimet më të fuqishme.");
println!("Njeriu me te vertete personalisht duhet te bjere nen hijen e luftes per te ndjere plotesisht shtypjen e saj;");
println!("por me kalimin e viteve, duket se tani shpesh harrohet se të kapeshe në rini deri në vitin 1914 nuk ishte një përvojë më pak e frikshme sesa të përfshiheshe në 1939 dhe vitet në vijim.");
println!("Në vitin 1918, të gjithë përveç njërit nga miqtë e mi të ngushtë kishin vdekur.");
println!("Ose për të marrë një çështje më pak të rëndë:");
println!("nga disa është supozuar se 'The Scouring of the Shire' pasqyron situatën në Angli në kohën kur unë po mbaroja përrallën time.");
println!("Nuk ka.");
println!("Është një pjesë thelbësore e komplotit, e parashikuar që në fillim, edhe pse në rastin e modifikuar nga personazhi i Saruman siç është zhvilluar në tregim pa");
println!("duhet të them, çfarëdo rëndësie alegorike apo referencë politike bashkëkohore.");
println!("Me të vërtetë ka një bazë në përvojë, edhe pse e hollë (sepse situata ekonomike ishte krejtësisht e ndryshme)");
println!("dhe shumë më mbrapa.");
println!("Vendi në të cilin jetoja në fëmijëri po shkatërrohej në mënyrë të shkretë para se të isha dhjetë vjeç,");
println!("në ditët kur makinat motorike ishin objekte të rralla (nuk e kisha parë kurrë) dhe burrat ende ndërtonin hekurudha periferike.");
println!("Kohët e fundit pashë në një gazetë një fotografi të varfërisë së fundit të mullirit të misrit dikur të lulëzuar pranë pishinës së tij që shumë kohë më parë më dukej kaq e rëndësishme.");
println!("Kurrë nuk më pëlqeu pamja e mullisit të ri, por babai i tij, mullixhiu i vjetër, kishte mjekër të zezë dhe nuk quhej Sandyman.");
println!("Zoti i unazave tani është botuar në një botim të ri dhe është shfrytëzuar mundësia për ta rishikuar.");
println!("Një numër gabimesh dhe mospërputhjesh që kanë mbetur ende në tekst janë korrigjuar,");
println!("dhe është bërë një përpjekje për të dhënë informacion për disa pika që lexuesit e vëmendshëm i kanë ngritur.");
println!("Kam shqyrtuar të gjitha komentet dhe pyetjet e tyre, dhe nëse disa duket se janë kaluar, kjo mund të jetë për shkak se nuk kam mbajtur shënimet e mia në rregull;");
println!("por shumë pyetjeve mund të përgjigjen vetëm me shtojca shtesë,");
println!("ose në të vërtetë nga prodhimi i një vëllimi shtesë që përmban shumë nga materiali që unë nuk e kam përfshirë në botimin origjinal,");
println!("në veçanti informacion më të detajuar gjuhësor.");
println!("Ndërkohë ky botim ofron këtë Parathënie, një shtesë në Prolog, disa shënime dhe një tregues të emrave të personave dhe vendeve.");
println!("Ky indeks është në qëllim i plotë në artikuj, por jo në referenca, pasi për qëllimin aktual ka qenë e nevojshme të zvogëlohet pjesa më e madhe e tij.");
println!("Një indeks i plotë, duke shfrytëzuar plotësisht materialin e përgatitur për mua nga zonja N. Smith, i përket më tepër vëllimit shtesë.");
println!("----------------------------------------------");
println!("PROLOG");
println!("Ky libër ka të bëjë kryesisht me Hobbitët, dhe nga faqet e tij një lexues mund të zbulojë shumë nga karakteri i tyre dhe pak nga historia e tyre.");
println!("Informacione të mëtejshme do të gjenden gjithashtu në përzgjedhjen nga Libri i Kuq i Westmarch që tashmë është botuar, nën titullin 'Hobit.'");
println!("Ajo histori është nxjerrë nga kapitujt e mëparshëm të Librit të Kuq, të kompozuar nga vetë Bilbo");
println!("Hobiti i parë që u bë i famshëm në botë në përgjithësi, dhe i thirrur nga ai Atje dhe Prapë");
println!("pasi treguan per udhetimin e tij ne Lindje dhe kthimin e tij:");
println!("një aventurë e cila më vonë përfshiu të gjithë Hobbitët në ngjarjet e mëdha të asaj Epoke që lidhen këtu.");
println!("Shumë, megjithatë, mund të dëshirojnë të dinë më shumë rreth këtij populli të shquar që në fillim, ndërsa disa mund të mos e posedojnë librin e mëparshëm.");
println!("Për lexues të tillë disa shënime mbi pikat më të rëndësishme janë mbledhur këtu nga Hobbit-lore, dhe aventura e parë kujtohet shkurtimisht.");
println!("Hobbitët janë një popull modest, por shumë i lashtë, më i shumtë më parë se sa janë sot;");
println!("sepse ata e duan paqen dhe qetesine dhe token e punuar mire:");
println!("një fshat i rregulluar dhe i kultivuar mirë ishte streha e tyre e preferuar.");
println!("Ata nuk kuptojnë dhe nuk i pëlqejnë ose pëlqejnë makineritë më të ndërlikuara se shakulli i falsifikimit,");
println!("një mulli uji, ose një vegjë dore, megjithëse ishin të zotë me veglat.");
println!("Edhe në kohët e lashta ata, si rregull, ishin të turpshëm nga 'populli i madh',");
println!("siç na thërrasin, dhe tani na shmangin me tmerr dhe po bëhen të vështirë për t'u gjetur.");
println!("Ata jane te shpejte ne degjim dhe me sy te mprehte, edhe pse jane te prirur per te trashur dhe nuk nxitojne pa nevoje");
println!("ata megjithatë janë të shkathët dhe të shkathët në lëvizjet e tyre.");
println!("Ata zotëronin që në fillim artin e zhdukjes së shpejtë dhe të heshtur,");
println!("kur njerez te medhenj te cilet nuk deshirojne t'i takojne gabojne;");
println!("dhe këtë e kanë zhvilluar derisa njerëzve mund t'u duket magjike.");
println!("Por Hobbitët, në fakt, kurrë nuk kanë studiuar magjinë e asnjë lloji,");
println!("dhe pakapshmëria e tyre është vetëm për shkak të një aftësie profesionale që trashëgojnë dhe praktikojnë,");
println!("dhe një miqësi e ngushtë me tokën, janë bërë të paimitueshme nga racat më të mëdha dhe më të ngathët.");
println!("Sepse ata jane njerez te vegjel, me te vegjel se Xhuxhit:");
println!("më pak të forta dhe të forta, domethënë, edhe kur në fakt nuk janë shumë më të shkurtra.");
println!("Lartësia e tyre është e ndryshueshme, varion midis dy dhe katër këmbëve të masës sonë.");
println!("Ata rrallëherë arrijnë deri në tre këmbë;");
println!("por ato u pakësuan, thonë ata, dhe në kohët e lashta ishin më të gjata.");
println!("Sipas Librit të Kuq, Bandobras Took (Bullroarer)");
println!("djali i Isengrimit te Dyte, ishte kater kembe e pese dhe i afte te hipte ne kale.");
println!("Ai u tejkalua në të gjitha rekordet e Hobbit vetëm nga dy personazhe të famshëm të vjetër;");
println!("por ajo çështje kurioze trajtohet në këtë libër.");
println!("Sa për Hobbitët e Shirit, me të cilët kanë të bëjnë këto përralla, në ditët e paqes dhe prosperitetit të tyre ata ishin një popull i gëzuar.");
println!("Ata visheshin me ngjyra të ndezura, duke qenë veçanërisht të dashur për të verdhën dhe jeshile;");
println!("por ata rrallë mbanin këpucë, pasi këmbët e tyre kishin thembra të forta prej lëkure dhe ishin të veshura me flokë të dendur të dredhur,");
println!("shumë si flokët e kokës së tyre, të cilat zakonisht ishin kafe.");
println!("Kështu, i vetmi zanat pak i praktikuar mes tyre ishte prodhimi i këpucëve;");
println!("por ata kishin gishta te gjate e te zote dhe mund te benin shume gjera te tjera te dobishme dhe te bukura.");
println!("Fytyrat e tyre ishin si rregull me natyrë të mirë dhe jo të bukura, të gjera, me sy të shndritshëm");
println!("me faqe te kuqe, me goje te pershtatshme per te qeshur dhe per te ngrene e pire.");
println!("Dhe qeshën, dhe hanin dhe pinë");
println!("shpesh dhe me gjithë zemër, duke qenë gjithmonë i dhënë pas shakave të thjeshta,");
println!("dhe gjashtë vakte në ditë (kur mund t'i merrnin)");
println!("Ata ishin mikprites dhe te kenaqur ne ahengje dhe ne dhurata, te cilat i jepnin lirisht dhe i pranonin me padurim.");
println!("Është vërtet e qartë se, pavarësisht nga largimi i mëvonshëm, Hobbitët janë të afërmit tanë:");
println!("shumë më afër nesh se kukudhët, apo edhe se xhuxhët.");
println!("Në kohët e lashta ata flisnin gjuhët e njerëzve, sipas mënyrës së tyre, dhe i pëlqenin dhe nuk i pëlqenin shumë të njëjtat gjëra si njerëzit.");
println!("Por çfarë saktësisht është marrëdhënia jonë nuk mund të zbulohet më.");
println!("Fillimi i Hobbit-it qëndron shumë larg në Ditët e Pleqve që tani janë humbur dhe harruar.");
println!("Vetëm Elfët ruajnë ende ndonjë regjistrim të asaj kohe të zhdukur dhe traditat e tyre kanë të bëjnë pothuajse tërësisht me historinë e tyre");
println!("në të cilën Burrat shfaqen rrallë dhe Hobitët nuk përmenden fare.");
println!("Megjithatë është e qartë se Hobitët, në fakt, kishin jetuar të qetë në Tokën e Mesme për shumë vite të gjata përpara se njerëzit e tjerë të dinin për ta.");
println!("Dhe bota është në fund të fundit plot me krijesa të çuditshme të pallogaritshme");
println!("këta njerëz të vegjël dukeshin me shumë pak rëndësi.");
println!("Por në kohën e Bilbos dhe të Frodos trashëgimtari i tij, ata u bënë befas, pa dëshirën e tyre");
println!("edhe te rendesishme dhe te njohura dhe te trazuara keshillat e te Urtit dhe te Madh.");
println!("Ato ditë, Epoka e Tretë e Tokës së Mesme, kanë kaluar shumë kohë dhe forma e të gjitha vendeve është ndryshuar;");
println!("por rajonet në të cilat Hobbit-ët atëherë jetonin ishin pa dyshim të njëjta me ato në të cilat ata ende qëndrojnë:");
println!("Veriperëndimi i Botës së Vjetër, në lindje të Detit.");
println!("Për shtëpinë e tyre origjinale, Hobitët në kohën e Bilbos nuk ruanin asnjë njohuri.");
println!("Dashuria për të mësuar (përveç njohurive gjenealogjike) ishte larg nga e zakonshme mes tyre,");
println!("por mbetën ende disa në familjet më të vjetra që studionin librat e tyre,");
println!("dhe madje mblodhi raporte të kohëve të vjetra dhe vendeve të largëta nga kukudhët, xhuxhët dhe njerëzit.");
println!("Të dhënat e tyre filluan vetëm pas vendosjes së Shire, dhe legjendat e tyre më të lashta vështirë se shikonin më tej se Ditët e tyre Endacake.");
println!("Megjithatë është e qartë nga këto legjenda dhe nga dëshmitë e fjalëve dhe zakoneve të tyre të veçanta,");
println!("që si shumë Hobbit të tjerë popullorë në të kaluarën e largët kishin lëvizur drejt perëndimit.");
println!("Tregimet e tyre më të hershme duket se tregojnë një kohë kur ata banonin në luginat e sipërme të Anduinit,");
println!("midis strehëve të Greenwood-it të Madh dhe Maleve të Mjegullta.");
println!("Pse ata më vonë ndërmorën kalimin e vështirë dhe të rrezikshëm të maleve në Eriador nuk është më e sigurt.");
println!("Rrëfimet e tyre flasin për shtimin e njerëzve në tokë dhe për një hije që ra në pyll, aq sa u errësua dhe emri i ri ishte Mirkwood.");
println!("Para se të kalonin malet, Hobitët tashmë ishin ndarë në tre raca disi të ndryshme:");
println!("Harfoots, Stoors dhe Fallohides.");
println!("Harfoots ishin me lekure me te zeze, me te vegjel dhe me te shkurter, dhe ishin pa mjeker dhe pa cizme;");
println!("duart dhe këmbët e tyre ishin të rregullta dhe të shkathëta;");
println!("dhe parapëlqenin malësitë dhe kodrat.");
println!("Stororët ishin më të gjerë, më të rëndë në ndërtim;");
println!("këmbët dhe duart e tyre ishin më të mëdha dhe preferonin tokat e sheshta dhe brigjet e lumenjve.");
println!("Fallohidët ishin më të bukur nga lëkura dhe gjithashtu nga flokët, dhe ata ishin më të gjatë dhe më të hollë se të tjerët;");
println!("ata ishin të dashuruar pas pemëve dhe pyjeve.");
println!("Harfootët kishin shumë të bënin me Xhuxhët në kohët e lashta dhe jetonin prej kohësh në rrëzë të maleve.");
println!("Ata u zhvendosën herët drejt perëndimit dhe bredhin mbi Eriador deri në Weathertop ndërsa të tjerët ishin ende në Tokën e egër.");
println!("Ata ishin varieteti më normal dhe më përfaqësues i Hobbit-it, dhe shumë më i shumti.");
println!("Ata ishin më të prirur për t'u vendosur në një vend dhe më gjatë e ruajtën zakonin e tyre stërgjyshorë për të jetuar në tunele dhe gropa.");
println!("Stoors zgjatën gjatë pranë brigjeve të lumit të madh Anduin dhe ishin më pak të trembur nga njerëzit.");
println!("Ata erdhën në perëndim pas Harfoots dhe ndoqën rrjedhën e Loudwater drejt jugut;");
println!("dhe shumë prej tyre banuan gjatë mes Tharbadit dhe kufijve të Dunlandit përpara se të lëviznin përsëri në veri.");
println!("Fallohidët, më pak të shumtë, ishin një degë veriore.");
println!("Ata ishin më miqësorë me kukudhët sesa hobitët e tjerë,");
println!("dhe kishte me shume zotesi ne gjuhe e kenge se sa ne zejtari;");
println!("dhe nga heret preferonin gjuetine sesa punimin.");
println!("Ata kaluan malet ne veri te Rivendellit dhe zbriten nga lumi Hoarwell.");
println!("Në Eriador shpejt u përzien me llojet e tjera që i kishin paraprirë,");
println!("por duke qenë disi më i guximshëm dhe më aventurier,");
println!("ato shpesh gjendeshin si udhëheqës ose prijës midis klaneve të Harfoots ose Stoors.");
println!("Edhe në kohën e Bilbos tendosja e fortë Fallohidish mund të vihej re ende në familjet më të mëdha,");
println!("të tilla si Tooks and the Masters of Buckland.");
println!("Në vendet perëndimore të Eriadorit, midis maleve të mjegullta dhe maleve të Lunës, Hobitët gjetën si burra ashtu edhe kukudhë.");
println!("Në të vërtetë, një mbetje ende banonte atje nga Dúnedain");
println!("mbretërit e njerëzve që erdhën përtej detit nga perëndimi;");
println!("por ata po pakësoheshin me shpejtësi dhe tokat e Mbretërisë së tyre Veriore po binin shumë e gjerë në shkreti.");
println!("Kishte vend dhe për të kursyer për të ardhurit, dhe shumë kohë Hobbit-ët filluan të vendoseshin në komunitete të renditura.");
println!("Shumica e vendbanimeve të tyre të mëparshme ishin zhdukur prej kohësh dhe ishin harruar në kohën e Bilbos;");
println!("por një nga të parët që u bë i rëndësishëm ende duroi, megjithëse i zvogëluar në madhësi;");
println!("kjo ishte në Bree dhe në Chetwood që shtrihej rreth e qark, rreth dyzet milje në lindje të Shire.");
println!("Ishte në këto ditë të hershme, pa dyshim,");
println!("që Hobitët mësuan shkronjat e tyre dhe filluan të shkruanin sipas mënyrës së Dúnedain,");
println!("që nga ana e tyre e kishin mësuar artin shumë kohë më parë nga kukudhët.");
println!("Dhe në ato ditë ata harruan gjithashtu të gjitha gjuhët që kishin përdorur më parë,");
println!("dhe foli gjithmonë pas fjalimit të përbashkët, Westron siç u quajt,");
println!("ajo ishte aktuale nëpër të gjitha vendet e mbretërve nga Arnor në Gondor,");
println!("dhe rreth të gjitha brigjeve të detit nga Belfalas në Lune.");
println!("Megjithatë ata mbajtën disa fjalë të tyre, si dhe emrat e tyre të muajve dhe ditëve,");
println!("dhe një magazinë e madhe emrash personalë nga e kaluara.");
println!("Rreth kësaj kohe legjenda mes Hobitëve bëhet fillimisht histori me llogaritjen e viteve.");
println!("Sepse ishte në vitin njëmijë e gjashtëqind e një të Epokës së Tretë që vëllezërit Fallohide, Marcho dhe Blanco, u nisën nga Bree;");
println!("dhe pasi mori leje nga mbreti i larte ne Fornost,");
println!("ata kaluan lumin kafe Baranduin me një ndjekje të madhe të Hobbits.");
println!("Ata kaluan mbi Urën e Harqeve të Gurit, që ishte ndërtuar në ditët e pushtetit të Mbretërisë së Veriut");
println!("dhe ata morën gjithë tokën përtej për të banuar, midis lumit dhe Downs së Largët.");
println!("E tëra ajo që u kërkua prej tyre ishte që ta mbanin Urën e Madhe në riparim,");
println!("dhe të gjitha urat dhe rrugët e tjera, shpejtoni lajmëtarët e mbretit dhe pranoni zotërimin e tij.");
println!("Kështu filloi llogaritja e Shire,");
println!("për vitin e kalimit të Brandywine (siç e kthyen emrin Hobbits) u bë Viti i parë i Shire,");
println!("dhe të gjitha datat e mëvonshme u llogaritën prej saj.");
println!("Menjëherë Hobbit-ët perëndimor ranë në dashuri me tokën e tyre të re dhe ata mbetën atje,");
println!("dhe shpejt kaloi edhe nje here nga historia e njerezve dhe e kukudheve.");
println!("Ndërsa kishte ende një mbret ata ishin në emër të nënshtetasve të tij, por në fakt ishin");
println!("të qeverisur nga krerët e tyre dhe të mos përzihen fare me ngjarjet në botën e jashtme.");
println!("Në betejën e fundit në Fornost me Magjistarin e Angmarit ata dërguan disa harkëtarë në ndihmë të mbretit");
println!("ose kështu kanë mbajtur ata, megjithëse asnjë tregim i Burrave nuk e regjistron atë.");
println!("Por në atë luftë mbaroi Mbretëria e Veriut;");
println!("dhe pastaj Hobbit-et e moren token per vete");
println!("dhe ata zgjodhën nga krerët e tyre një Thain për të mbajtur autoritetin e mbretit që kishte ikur.");
println!("Atje për një mijë vjet ata ishin pak të shqetësuar nga luftërat,");
println!("dhe ata përparuan dhe u shumuan pas Murtajës së Errët (S.R. 37) deri në fatkeqësinë e dimrit të gjatë dhe zinë e bukës që pasoi atë.");
println!("Më pas humbën shumë mijëra");
println!("por Ditët e Vdekjes (1158-60) ishin në kohën e kësaj përrallë e kaluara shumë e gjatë dhe Hobbitët ishin mësuar përsëri me bollëkun.");
println!("Toka ishte e pasur dhe e sjellshme, edhe pse prej kohesh ishte e shkrete kur ata hyne ne te");
println!("ajo ishte punuar mirë më parë dhe atje mbreti dikur kishte pasur shumë ferma, toka misri, vreshta dhe pyje.");
println!("Dyzet liga u shtri nga Far Downs deri te Ura Brandywine,");
println!("dhe pesedhjete nga malet veriore deri ne kenetat ne jug.");
println!("Hobbitët e quajtën atë Shire, si rajoni i autoritetit të Thain të tyre,");
println!("dhe një distrikt biznesi të rregulluar mirë;");
println!("dhe atje në atë ardhjen e këndshme të botës ata aplikuan biznesin e tyre të rregulluar mirë të jetesës,");
println!("dhe ata ia vunë veshin gjithnjë e më pak botës jashtë ku gjërat e errëta lëviznin,");
println!("derisa ata arritën të mendonin se paqja dhe bollëku ishin rregulli në Tokën e Mesme dhe e drejta e të gjithë njerëzve të arsyeshëm.");
println!("Ata harruan ose shpërfillën atë pak që kishin ditur ndonjëherë për Ruajtësit,");
println!("dhe nga puna e atyre qe bene te mundur paqen e gjate te Shire.");
println!("Ata, në fakt, ishin të strehuar, por nuk e mbanin më në mend.");
println!("Asnjëherë Hobbitët e çfarëdo lloji nuk kanë qenë luftarakë");
println!("dhe ata nuk kishin luftuar kurre mes tyre.");
println!("Në kohët e vjetra ata kishin, natyrisht,");
println!("shpesh kanë qenë të detyruar të luftojnë për të ruajtur veten në një botë të vështirë;");
println!("por në kohën e Bilbos ishte histori shumë e lashtë.");
println!("Beteja e fundit, para se te hapet kjo histori");
println!("dhe me të vërtetë i vetmi që ishte luftuar ndonjëherë brenda kufijve të Shire,");
println!("ishte përtej kujtesës së gjallë:");
println!("Beteja e Greenfields, S.R. 1147, në të cilën Bandobras Took shkatërroi një pushtim të Orcëve.");
println!("Edhe moti ishte bërë më i butë,");
println!("dhe ujqërit që dikur kishin dalë duke grabitur nga Veriu në dimra të bardhë të hidhur, tani ishin vetëm një përrallë e gjyshit.");
println!("Pra, edhe pse kishte ende disa armë në Shire, këto përdoreshin kryesisht si trofe,");
println!("varur mbi vatra ose në mure, ose mbledhur në muzeun në Michel Delving.");
println!("Shtëpia Mathom quhej;");
println!("për çdo gjë që Hobbits nuk kishte asnjë përdorim të menjëhershëm,");
println!("por nuk donin ta hidhnin, e quajtën math.");
println!("Banesat e tyre ishin të përshtatshme për t'u mbushur plot me math,");
println!("dhe shumë nga dhuratat që kalonin nga dora në dorë ishin të atij djalit.");
println!("Megjithatë, lehtësia dhe paqja e kishin lënë këtë popull ende kuriozisht të ashpër.");
println!("Ata, po të vinte në punë, ishin të vështira për t'u trembur ose për të vrarë;");
println!("dhe ata, ndoshta, ishin aq të palodhur pas gjërave të mira, jo vetëm sepse mundeshin,");
println!("kur vihet në punë, bëje pa to dhe mund t'i mbijetosh trajtimit të ashpër nga pikëllimi,");
println!("armiku, ose moti në një mënyrë që i habiti ata që nuk i njihnin mirë dhe nuk shikonin më larg se barqet e tyre dhe fytyrat e tyre të ushqyera mirë.");
println!("Megjithëse i ngadalshëm në grindje, dhe për sport vrasja e asgjëje që jetoi,");
println!("ata ishin brumë në gji dhe në nevojë ende mund të mbanin armë.");
println!("Ata qëlluan mirë me hark, sepse ishin sy të mprehtë dhe të sigurt në shenjë.");
println!("Jo vetem me harqe e shigjeta.");
println!("Nëse ndonjë Hobbit u përkul për një gur,");
println!("ishte mirë të mbulohesha shpejt");
println!("siç e dinin shumë mirë të gjitha bishat shkelëse.");
println!("Të gjithë Hobitët kishin jetuar fillimisht në vrima në tokë, ose kështu besonin ata,");
println!("dhe ne banesa te tilla akoma ndjeheshin me se shumti si ne shtepine e tyre;");
println!("por me kalimin e kohes ata ishin detyruar te adoptonin forma te tjera banimi.");
println!("Në të vërtetë në Shire në kohën e Bilbos ishte, si rregull,");
println!("vetëm Hobbitët më të pasur dhe më të varfër që ruanin zakonin e vjetër.");
println!("Më të varfërit vazhduan të jetonin në strofulla të llojit më primitiv, në të vërtetë vrima të thjeshta, me vetëm një dritare ose asnjë;");
println!("ndërsa të pasurit ende ndërtonin versione më luksoze të gërmimeve të thjeshta të dikurshme.");
println!("Por vende të përshtatshme për këto tunele të mëdha dhe degëzuese (ose smials siç i quanin ata) nuk gjendeshin kudo;");
println!("dhe në banesa dhe në lagjet e ulëta Hobbits,");
println!("si u shumuan, filluan te ndertohen mbi toke.");
println!("Me te vertete edhe ne zonat kodrinore dhe ne fshatrat e vjetra");
println!("të tilla si Hobbiton ose Tuckborough, ose në qytetin kryesor të Shire,");
println!("Michel Delving në White Downs, tani kishte shumë shtëpi prej druri, tullash ose guri.");
println!("Këto favorizoheshin posaçërisht nga mullixhinjtë, farkëtarët, litarët dhe karrocierët dhe të tjerë të këtij lloji;");
println!("sepse edhe kur kishin vrima per te jetuar.");
println!("Hobbitët ishin mësuar prej kohësh të ndërtonin kasolle dhe punishte.");
println!("Zeoni i ndërtimit të shtëpive të fermave dhe hambarëve thuhej se kishte filluar te banorët e Marish poshtë nga Brandywine.");
println!("Hobitët e asaj lagjeje, Lindja e Farthing");
println!("ishin mjaft të mëdhenj dhe me këmbë të rënda,");
println!("dhe mbanin çizme xhuxhi ne mot me balte.");
println!("Por ata njiheshin mirë se ishin Stoors në një pjesë të madhe të gjakut të tyre,");
println!("siç u tregua me të vërtetë nga poshtë se shumë u rritën në mjekrën e tyre.");
println!("Asnjë Harfoot apo Fallohide nuk kishte asnjë gjurmë mjekër.");
println!("Në të vërtetë, populli i Marish-it dhe i Buckland-it, në lindje të lumit, të cilin ata e pushtuan më pas,");
println!("erdhi në pjesën më të madhe më vonë në Shire nga jugu;");
println!("dhe ata kishin ende shumë emra të veçantë dhe fjalë të çuditshme që nuk gjenden diku tjetër në Shire.");
println!("Ka të ngjarë që zanati i ndërtimit, si shumë zanate të tjera përveç, të ketë ardhur nga Dunedain.");
println!("Por Hobitët mund ta kenë mësuar atë drejtpërdrejt nga Elfët, mësuesit e njerëzve në rininë e tyre.");
println!("Sepse kukudhët e fisit të lartë nuk e kishin braktisur ende Tokën e Mesme");
println!("dhe ata banonin ende në atë kohë në Parajsat Gri larg në perëndim,");
println!("dhe në vende të tjera brenda mundësive të Shire.");
println!("Tre kullat e Elfeve të epokës së lashtë do të shiheshin ende në kodrat e Kullës përtej marshimeve perëndimore.");
println!("Ata shkëlqenin larg në dritën e hënës.");
println!("Më i gjati ishte më larg, qëndronte i vetëm mbi një tumë të gjelbër.");
println!("Hobitët e Westfarthing-ut thanë se mund të shihej deti nga lopata e asaj kulle;");
println!("por asnjë Hobbit nuk ishte njohur ndonjëherë për t'u ngjitur në të.");
println!("Në të vërtetë, pak hobitë kishin parë ose lundruar në det");
println!("dhe më pak ishin kthyer ndonjëherë për ta raportuar atë.");
println!("Shumica e Hobitëve i konsideronin edhe lumenjtë dhe varkat e vogla me dyshime të thella,");
println!("dhe jo shumë prej tyre mund të notonin.");
println!("Dhe me zgjatjen e ditëve të Shirit ata flisnin gjithnjë e më pak me kukudhët");
println!("dhe u frikësua prej tyre dhe nuk u besua atyre që kishin marrëdhënie me ta;");
println!("Dhe Deti u be nje fjale frike midis tyre dhe nje shenje vdekjeje");
println!("dhe i kthyen fytyrat nga kodrat ne perendim.");
println!("Zija e ndërtimit mund të ketë ardhur nga kukudhët ose njerëzit, por Hobbitët e përdorën atë në mënyrën e tyre.");
println!("Nuk hyne per kulla.");
println!("Shtëpitë e tyre ishin zakonisht të gjata, të ulëta dhe komode.");
println!("Lloji më i vjetër nuk ishin, në të vërtetë, vetëm imitime të ndërtuara të smials,");
println!("e mbuluar me bar të thatë ose kashtë, ose me çati me kthesa dhe me mure disi të fryrë.");
println!("Ajo fazë, megjithatë, i përkiste ditëve të hershme të Shire");
println!("dhe ndërtimi i hobbit-it ishte ndryshuar prej kohësh, përmirësuar nga pajisjet,");
println!("mësuar nga Xhuxhët, ose zbuluar nga vetë ata.");
println!("Preferenca për dritaret e rrumbullakëta, madje edhe dyert e rrumbullakëta, ishte veçoria kryesore e mbetur e arkitekturës hobbit.");
println!("Shtëpitë dhe gropat e Shire-hobitëve ishin shpesh të mëdha dhe të banuara nga familje të mëdha.");
println!("(Bilbo dhe Frodo Baggins ishin si beqarë shumë të jashtëzakonshëm, siç ishin edhe në shumë mënyra të tjera, si miqësia e tyre me kukudhët.)");
println!("Ndonjëherë, si në rastin e 'Toks of Great Smials'");
println!("ose Brandybucks of Brandy Hall,");
println!("shumë breza të afërmsh jetonin në paqe (krahasuese) së bashku në një rezidencë stërgjyshore dhe me shumë tunele.");
println!("Të gjithë Hobitët ishin, në çdo rast, klani dhe i vlerësonin marrëdhëniet e tyre me shumë kujdes.");
println!("Ata vizatuan pemë familjare të gjata dhe të përpunuara me degë të panumërta.");
println!("Në marrëdhëniet me Hobbitët është e rëndësishme të mbani mend se kush është i lidhur me kë dhe në çfarë shkalle.");
println!("Do të ishte e pamundur në këtë libër të përcaktohej një pemë familjare që përfshinte edhe anëtarët më të rëndësishëm të familjeve më të rëndësishme në atë kohë për të cilat flasin këto përralla.");
println!("Pemët gjenealogjike në fund të Librit të Kuq të Westmarch janë një libër i vogël në vetvete,");
println!("dhe të gjithë përveç Hobitëve do t'i gjenin jashtëzakonisht të mërzitshme.");
println!("Hobbitët kënaqeshin me gjëra të tilla, po të ishin të sakta:");
println!("atyre u pëlqente të kishin libra të mbushur me gjëra që ata tashmë i dinin,");
println!("përcakto i drejtë dhe katror pa kontradikta.");
println!("Ka një gjë tjetër të habitshme për Hobbitët e lashtë që duhet përmendur, një zakon i habitshëm:");
println!("ata thithën ose thithën, përmes tubave prej balte ose druri,");
println!("tymi i gjetheve te djegura te nje bari, te cilen e quanin gyp ose gjethe");
println!("një varietet ndoshta i Nikotianës.");
println!("Një mister i madh rrethon origjinën e këtij zakoni të veçantë,");
println!("ose 'art' siç preferuan ta quajnë Hobbit-ët.");
println!("Gjithçka që mund të zbulohej për të në antikitet u mblodh nga Meriadoc Brandybuck (më vonë Master i Buckland)");
println!("dhe meqenëse ai dhe duhani i Jugut luajnë një rol në historinë që vijon,");
println!("vërejtjet e tij në hyrje të tij Herblore of the Shire mund të citohen.");
println!("Ky, thotë ai, është i vetmi art që ne me siguri mund të pretendojmë se është shpikja jonë.");
println!("Nuk dihet kur hobitët filluan të pinin duhan");
println!("të gjitha legjendat dhe historitë familjare e marrin si të mirëqenë;");
println!("për shekuj me radhë njerëzit në Shire tymosnin barishte të ndryshme, disa më të ndyra, disa më të ëmbla.");
println!("Por të gjitha rrëfimet bien dakord që Tobold Hornblower nga Longbottom në Southfarthing për herë të parë rriti barërat e këqija të vërtetë në kopshtet e tij në ditët e Isengrimit të Dytë,");
println!("rreth vitit 1070 te llogaritjes Shire.");
println!("Më të mirat në shtëpi vijnë ende nga ai distrikt,");
println!("veçanërisht varietetet e njohura tani si Longbottom Leaf, Old Toby dhe Southern Star.");
println!("Sa i vjetër Tobi erdhi nga uzina nuk është regjistruar, sepse deri në ditën e tij të vdekjes ai nuk do të thoshte.");
println!("Ai dinte shumë për barishtet, por nuk ishte udhëtar.");
println!("Thuhet se ne rini ka shkuar shpesh ne Bree");
println!("megjithëse ai me siguri nuk shkoi kurrë më larg nga Shire se kaq.");
println!("Kështu është shumë e mundur që ai të mësojë për këtë bimë në Bree, ku tani, në çdo rast,");
println!("rritet mire ne shpatet jugore te kodres.");
println!("Hobitët Bree pretendojnë se kanë qenë duhanpirësit e parë të vërtetë të pipëzave.");
println!("Ata pohojnë, sigurisht, se kanë bërë gjithçka përpara banorëve të Shirit");
println!("të cilëve ata i referohen si 'kolonistë';");
println!("por në këtë rast pretendimi i tyre, mendoj, ka të ngjarë të jetë i vërtetë.");
println!("Dhe sigurisht që ishte nga Bree që arti i tymosjes së barërave të këqija u përhap në shekujt e fundit midis xhuxhëve dhe njerëzve të tjerë të tillë,");
println!("Rengers, Wizards, ose Endaders, siç kalonin ende andej këndej nëpër atë takim të lashtë rrugor.");
println!("Shtëpia dhe qendra e anit mund të gjenden kështu në bujtinë e vjetër të Bree,");
println!("Poni i Prancing, që është mbajtur nga familja e Butterbur-it prej kohësh që nuk është regjistruar.");
println!("Gjithçka njësoj,");
println!("vëzhgimet që kam bërë gjatë udhëtimeve të mia të shumta në jug më kanë bindur se vetë barërat e këqija nuk janë vendase në pjesët tona të botës,");
println!("por erdhi në veri nga Anduin e poshtëm, ku ishte, dyshoj,");
println!("i sjellë fillimisht mbi Det nga Burrat e Westernesse.");
println!("Rritet me bollëk në Gondor dhe atje është më i pasur dhe më i madh se në Veri,");
println!("ku nuk gjendet kurrë i egër dhe lulëzon vetëm në vende të ngrohta të strehuara si Longbottom.");
println!("Njerëzit e Gondorit e quajnë galena të ëmbël dhe e vlerësojnë vetëm për aromën e luleve të tij.");
println!("Nga ajo tokë duhet të jetë marrë deri në Greenway gjatë shekujve të gjatë midis ardhjes së Elendilit dhe ditëve tona.");
println!("Por edhe Dúnedain e Gondorit na e lejon këtë meritë:");
println!("Hobbits fillimisht e vendosin ne tuba.");
println!("As Magjistarët nuk e menduan fillimisht këtë para ne.");
println!("Megjithëse një magjistar që e njihja e mori artin shumë kohë më parë dhe u bë po aq i aftë në të sa në të gjitha gjërat e tjera për të cilat kishte menduar.");
println!("Shire u nda në katër lagje, Farthings tashmë përmendur.");
println!("Veri, Jug, Lindje dhe Perëndim;");
println!("dhe këto përsëri secili në një numër folklandesh,");
println!("që ende mbante emrat e disa prej familjeve të vjetra udhëheqëse");
println!("edhe pse në kohën e kësaj historie këta emra nuk gjendeshin më vetëm në tokat e tyre popullore.");
println!("Pothuajse të gjithë Tooks ende jetonin në Tookland,");
println!("por kjo nuk ishte e vërtetë për shumë familje të tjera,");
println!("të tilla si Bagginses ose Boffins.");
println!("Jashtë Farthings ishin marshimet e Lindjes dhe Perëndimit:");
println!("The Buckland (shih fillimin e Kapitullit Pesë, Libri i Parë);");
println!("dhe Westmarch i shtoi Shire në S.R. 1462.");
println!("Shire në këtë kohë nuk kishte pothuajse asnjë 'qeveri'.");
println!("Familjet në pjesën më të madhe i menaxhonin punët e tyre.");
println!("Rritja e ushqimit dhe ngrënia e tij zinte shumicën e kohës.");
println!("Në çështje të tjera ata, si rregull, ishin bujarë dhe jo lakmitarë");
println!("por i kënaqur dhe i moderuar, kështu që prona, ferma, punishte,");
println!("dhe tregtitë e vogla prireshin të mbeten të pandryshuara për breza.");
println!("Natyrisht, mbeti tradita e lashtë në lidhje me mbretin e lartë në Fornost,");
println!("ose Norbury siç e quanin, larg në veri të Shire.");
println!("Por nuk kishte asnjë mbret për gati një mijë vjet");
println!("dhe madje edhe rrënojat e Kings' Norbury u mbuluan me bar.");
println!("Megjithatë Hobitët ende thoshin për gjërat e egra dhe të liga (si p.sh. trollët) që nuk kishin dëgjuar për mbretin.");
println!("Sepse ata ia atribuonin mbretit të lashtë të gjitha ligjet e tyre thelbësore;");
println!("dhe zakonisht ata mbanin ligjet e vullnetit te lire,");
println!("sepse ato ishin Rregullat (siç thanë)");
println!("si i lashtë ashtu edhe i drejtë.");
println!("Është e vërtetë që familja Took kishte qenë prej kohësh e shquar;");
println!("sepse zyra e Thain u kishte kaluar atyre (nga Oldbucks) disa shekuj më parë,");
println!("dhe shefi Took e kishte mbajtur atë titull që atëherë.");
println!("Tajni ishte mjeshtri i Shire-moot");
println!("dhe kapiteni i Shire-muster dhe Hobbitry-in-arms,");
println!("por si grumbullim dhe diskutim u mbajt vetëm në kohë emergjence,");
println!("që nuk ndodhi më,");
println!("Tajinshipi kishte pushuar së qeni më shumë se një dinjitet nominal.");
println!("Familja Took ende, me të vërtetë, i kushtonte një respekt të veçantë,");
println!("sepse mbeti i shumte dhe jashtezakonisht i pasur");
println!("dhe ishte i prirur të prodhonte në çdo brez karaktere të forta zakonesh të veçanta dhe madje edhe temperament aventureske.");
println!("Cilësitë e fundit, megjithatë, tani më tepër toleroheshin (në të pasurit) sesa miratoheshin përgjithësisht.");
println!("Megjithatë vazhdoi zakoni i referimit të kryefamiljarit si The Took dhe i shtimit të emrit të tij, nëse kërkohet, një numër:");
println!("të tilla si Isengrim i Dytë, për shembull.");
println!("I vetmi zyrtar i vërtetë në Shire në këtë datë ishte kryetari i bashkisë së Michel Delving (ose i Shire)");
println!("i cili zgjidhej çdo shtatë vjet në Panairin e Lirë në White Downs në Lithe,");
println!("që është në mes të verës.");
println!("Si kryetar bashkie pothuajse detyra e tij e vetme ishte të kryesonte bankete");
println!("dhene ne festat e Shire, qe ndodhnin ne intervale te shpeshta.");
println!("Por zyrat e Postmaster dhe First Shirriff i ishin bashkangjitur bashkise");
println!("kështu që ai menaxhoi si Shërbimin e Messengerit ashtu edhe Watch.");
println!("Këto ishin të vetmet shërbime Shire,");
println!("dhe te derguarit ishin me te shumte");
println!("dhe shumë më i ngarkuari nga të dyja.");
println!("Në asnjë mënyrë të gjithë Hobbitët nuk ishin me germa,");
println!("por ata që u shkruanin vazhdimisht të gjithë miqve të tyre (dhe një përzgjedhje të marrëdhënieve të tyre) që jetonin më larg se një shëtitje pasdite.");

























println!("Dalje?");
/*
The Shirriffs was the name that the Hobbits gave to their police, or the nearest equivalent that they possessed. They had, of course, no uniforms (such things being quite unknown), only a feather in their caps; and they were in practice rather haywards than policemen, more concerned with the strayings of beasts than of people. There were in all the Shire only twelve of them, three in each Farthing, for Inside Work. A rather larger body, varying at need, was employed to 'beat the bounds', and to see that Outsiders of any kind, great or small, did not make themselves a nuisance.
At the time when this story begins the Bounders, as they were called, had been greatly increased. There were many reports and complaints of strange persons and creatures prowling about the borders, or over them: the first sign that all was not quite as it should be, and always had been except in tales and legends of long ago. Few heeded the sign, and not even Bilbo yet had any notion of what it portended. Sixty years had passed since he set out on his memorable journey, and he was old even for Hobbits, who reached a hundred as often as not; but much evidently still remained of the considerable wealth that he had brought back. How much or how little he revealed to no one, not even to Frodo his favourite 'nephew'. And he still kept secret the ring that he bad found.
*/


//println!("\n");
/*
println!("Chinese Version:");
println!("J.R.R.托尔金 - 指环王。 (1/4)");
println!("-----------------------------------------------");
println!("指环王");
println!("经过");
println!("J·R·R·托尔金");
println!("第 1 部分：魔戒远征队");
println!("第二部分：两座塔");
println!("第三部分：王者归来");
println!("包含索引和完整附录");
println!("天空下精灵王的三枚戒指，");
println!("七个矮人领主在他们的石头大厅里，");
println!("九个注定要死的凡人，");
println!("一张献给坐在黑暗王座上的黑魔王，");
println!("在暗影所在的魔多之地。");
println!("一环统治他们所有人，一环找到他们，");
println!("一枚戒指将他们全部带入并在黑暗中束缚他们，");
println!("在暗影所在的魔多之地。");
println!("内容");
println!("前言");
println!("序幕");
println!("1.关于霍比特人");
println!("2. 关于管道杂草");
println!("3. 夏尔的秩序");
println!("4. 关于戒指的发现");
println!("关于夏尔记录的注释");
println!("戒指的团契");
println!("第一册");
println!("第一章 期待已久的聚会");
println!("第二章：过去的阴影");
println!("第三章 三是公司");
println!("第四章：通往蘑菇的捷径");
println!("第五章 阴谋败露");
println!("第六章：古老的森林");
println!("第七章：在汤姆·庞巴迪尔的家里");
println!("第八章：巴罗丘陵上的雾气");
println!("第九章 跃跃小马的标志");
println!("第十章：行者");
println!("第十一章 黑暗中的一把刀");
println!("第十二章 飞往福特");
println!("第二册：");
println!("第一章：多次会议");
println!("第二章：埃尔隆德会议");
println!("第三章：指环南下");
println!("第四章 黑暗之旅");
println!("第五章：卡扎杜姆之桥");
println!("第六章：洛斯罗立安");
println!("第七章：凯兰崔尔之镜");
println!("第八章：告别罗瑞恩");
println!("第九章 大河");
println!("第十章 团契的破裂");
println!("两座塔楼");
println!("第三册：");
println!("第一章 波罗米尔的离开");
println!("第二章：洛汗骑士");
println!("第三章：乌鲁克海");
println!("第四章：树须");
println!("第五章：白骑士");
println!("Chapter Six: The King of the Golden Hall");
println!("Chapter Seven: Helm's Deep");
println!("Chapter Eight: The Road to Isengard");
println!("Chapter Nine: Flotsam and Jetsam");
println!("Chapter Ten: The Voice of Saruman");
println!("Chapter Eleven: The Palantir");
println!("Book Four:");
println!("Chapter One: The Taming of Sméagol");
println!("Chapter Two: The Passage of the Marshes");
println!("Chapter Three: The Black Gate is Closed");
println!("Chapter Four: Of Herbs and Stewed Rabbit");
println!("Chapter Five: The Window on the West");
println!("Chapter Six: The Forbidden Pool");
println!("Chapter Seven: Journey to the Cross-roads");
println!("Chapter Eight: The Stairs of Cirith Ungol");
println!("Chapter Nine: Shelob's Lair");
println!("Chapter Ten: The Choices of Master Samwise");
println!("THE RETURN OF THE KING");
println!("Book Five:");
println!("Chapter 1 Minas Tirith");
println!("Chapter 2 The Passing of the Grey Company");
println!("Chapter 3 The Muster of Rohan");
println!("Chapter 4 The Siege of Gondor");
println!("Chapter 5 The Ride of the Rohirrim");
println!("Chapter 6 The Battle of the Pelennor Fields");
println!("Chapter 7 The Pyre of Denethor");
println!("Chapter 8 The Houses of Healing");
println!("Chapter 9 The Last Debate");
println!("Chapter 10 The Black Gate Opens");
println!("Book Six:");
println!("Chapter 1 The Tower of Cirith Ungol");
println!("Chapter 2 The Land of Shadow");
println!("Chapter 3 Mount Doom");
println!("Chapter 4 The Field of Cormallen");
println!("Chapter 5 The Steward and the King");
println!("Chapter 6 Many Partings");
println!("Chapter 7 Homeward Bound");
println!("Chapter 8 The Scouring of the Shire");
println!("Chapter 9 The Grey Havens");
*/
























//println!("Exit?");
io::stdin().read_line(&mut Exit);
}
