use std::io;
fn main() {
let _one_ring_poem_line_one = String::new();
let _contents = String::new();
let _foreword = String::new();
let _prologue = String::new();
let _by = String::new();
let mut exit = String::new();
let _period = String::new();
let _exit_input = String::new();
//let mut Language_Choice = String::new();



let _one_ring_poem_line_one = "Three Rings for the Elven-kings under the sky,";
let _contents = "CONTENTS";
let _foreword = "FOREWORD";
let _prologue = "PROLOGUE";
let _by = "by";
let _period = ".";
//Exit = "";

/*
println!("Your Current Language Options Are:");
println!("English (United States), and Chinese (Simplified)");
println!("Which Language Would You Like To Read This In?");
io::stdin().read_line(&mut Language_Choice);
*/

//if Language_Choice == "English" {
println!("English Version:");
println!("J. R. R. Tolkien - The Lord Of The Rings.");
println!("(One of Four)");
println!("-----------------------------------------------");
println!("THE LORD OF THE RINGS");
println!("{}", _by);
println!("J. R. R. TOLKIEN");
println!("Part One: The Fellowship of the Ring");
println!("Part Two: The Two Towers");
println!("Part Three: The Return of the King");
println!("Complete with Index and Full Appendices");
println!("{}", _one_ring_poem_line_one);
println!("Seven for the Dwarf-lords in their halls of stone,");
println!("Nine for Mortal Men doomed to die,");
println!("One for the Dark Lord on his dark throne,");
println!("In the Land of Mordor where the Shadows lie.");
println!("One Ring to rule them all,");
println!("One Ring to find them,");
println!("One Ring to bring them all and in the darkness bind them,");
println!("In the Land of Mordor where the Shadows lie.");
println!("{}", _contents);
println!("{}", _foreword);
println!("{}", _prologue);
println!("One: Concerning Hobbits");
println!("Two: Concerning Pipe-weed");
println!("Three: Of the Ordering of the Shire");
println!("Four: Of the Finding of the Ring");
println!("Note on the Shire records");
println!("THE FELLOWSHIP OF THE RING");
println!("Book One:");
println!("Chapter One: A Long-expected Party");
println!("Chapter Two: The Shadow of the Past");
println!("Chapter Three: Three is Company");
println!("Chapter Four: A Short Cut to Mushrooms");
println!("Chapter Five: A Conspiracy Unmasked");
println!("Chapter Six: The Old Forest");
println!("Chapter Seven: In the House of Tom Bombadil");
println!("Chapter Eight: Fog on the Barrow-Downs");
println!("Chapter Nine: At the Sign of The Prancing Pony");
println!("Chapter Ten: Strider");
println!("Chapter Eleven: A Knife in the Dark");
println!("Chapter Twelve: Flight to the Ford");
println!("Book Two:");
println!("Chapter One: Many Meetings");
println!("Chapter Two: The Council of Elrond");
println!("Chapter Three: The Ring Goes South");
println!("Chapter Four: A Journey in the Dark");
println!("Chapter Five: The Bridge of Khazad-dûm");
println!("Chapter Six: Lothlórien");
println!("Chapter Seven: The Mirror of Galadriel");
println!("Chapter Eight: Farewell to Lórien");
println!("Chapter Nine: The Great River");
println!("Chapter Ten: The Breaking of the Fellowship");
println!("THE TWO TOWERS");
println!("Book Three:");
println!("Chapter One: The Departure of Boromir");
println!("Chapter Two: The Riders of Rohan");
println!("Chapter Three: The Uruk-Hai");
println!("Chapter Four: Treebeard");
println!("Chapter Five: The White Rider");
println!("Chapter Six: The King of the Golden Hall");
println!("Chapter Seven: Helm's Deep");
println!("Chapter Eight: The Road to Isengard");
println!("Chapter Nine: Flotsam and Jetsam");
println!("Chapter Ten: The Voice of Saruman");
println!("Chapter Eleven: The Palantir");
println!("Book Four:");
println!("Chapter One: The Taming of Sméagol");
println!("Chapter Two: The Passage of the Marshes");
println!("Chapter Three: The Black Gate is Closed");
println!("Chapter Four: Of Herbs and Stewed Rabbit");
println!("Chapter Five: The Window on the West");
println!("Chapter Six: The Forbidden Pool");
println!("Chapter Seven: Journey to the Cross-roads");
println!("Chapter Eight: The Stairs of Cirith Ungol");
println!("Chapter Nine: Shelob's Lair");
println!("Chapter Ten: The Choices of Master Samwise");
println!("THE RETURN OF THE KING");
println!("Book Five:");
println!("Chapter One: Minas Tirith");
println!("Chapter Two: The Passing of the Grey Company");
println!("Chapter Three: The Muster of Rohan");
println!("Chapter Four: The Siege of Gondor");
println!("Chapter Five: The Ride of the Rohirrim");
println!("Chapter Six: The Battle of the Pelennor Fields");
println!("Chapter Seven: The Pyre of Denethor");
println!("Chapter Eight: The Houses of Healing");
println!("Chapter Nine: The Last Debate");
println!("Chapter Ten: The Black Gate Opens");
println!("Book Six:");
println!("Chapter One: The Tower of Cirith Ungol");
println!("Chapter Two: The Land of Shadow");
println!("Chapter Three: Mount Doom");
println!("Chapter Four: The Field of Cormallen");
println!("Chapter Five: The Steward and the King");
println!("Chapter Six: Many Partings");
println!("Chapter Seven: Homeward Bound");
println!("Chapter Eight: The Scouring of the Shire");
println!("Chapter Nine: The Grey Havens");
println!("APPENDICES");
println!("A");
println!("ANNALS OF THE KINGS AND RULERS");
println!("One: The Númenorean Kings");
println!("(One) Númenor");
println!("(Two) The Realms In Exile");
println!("(Three) Eriador, Arnor, and The Heirs Of Isildur");
println!("(Four) Gondor and The Heirs Of Anñrion");
println!("(Five) Here Follows a Part of The Tale of Aragorn and Arwen");
println!("Two: THE HOUSE  OF EORL");
println!("Three: DURIN'S FOLK");
println!("Here follows one of the last notes in the Red Book");
println!("B");
println!("THE TALE OF YEARS");
println!("(CHRONOLOGY OF THE WESTLANDS)");
println!("The Second Age");
println!("The Third Age");
println!("C");
println!("FAMILY TREES");
println!("D");
println!("CALENDARS");
println!("SHIRE CALENDAR FOR USE IN ALL YEARS");
println!("THE CALENDARS");
println!("E");
println!("WRITING AND SPELLING");
println!("One: Pronunciation of Words and Names");
println!("Two: Writing");
println!("F");
println!("One: The Languages and Peoples of The Third Age");
println!("Two: On Translation");
println!("INDEXES");
println!("One: Songs and Verses");
println!("Two: Persons, Beasts and Monsters");
println!("Three: Places");
println!("Four: Things");
println!("----------------------------------------------");
println!("FOREWORD");
println!("This tale grew in the telling, until it became a history of the Great War of the Ring and included many glimpses of the yet more ancient history that preceded it.");
println!("It was begun soon after The Hobbit was written and before its publication in Nineteen Thirty Seven;");
println!("but I did not go on with this sequel, for I wished first to complete and set in order the mythology and legends of the Elder Days, which had then been taking shape for some years.");
println!("I desired to do this for my own satisfaction, and I had little hope that other people would be interested in this work,");
println!("especially since it was primarily linguistic in inspiration and was begun in order to provide the necessary background of 'history' for Elvish tongues.");
println!("When those whose advice and opinion I sought corrected little hope to no hope, I went back to the sequel,");
println!("encouraged by requests from readers for more information concerning hobbits and their adventures.");
println!("But the story was drawn irresistibly towards the older world, and became an account, as it were, of its end and passing away before its beginning and middle had been told.");
println!("The process had begun in the writing of The Hobbit, in which there were already some references to the older matter:");
println!("Elrond, Gondolin, the High-elves, and the orcs, as well as glimpses that had arisen unbidden of things higher or deeper or darker than its surface:");
println!("Durin, Moria, Gandalf, the Necromancer, the Ring.");
println!("The discovery of the significance of these glimpses and of their relation to the ancient histories revealed the Third Age and its culmination in the War of the Ring.");
println!("Those who had asked for more information about hobbits eventually got it, but they had to wait a long time;");
println!("for the composition of The Lord of the Rings went on at intervals during the years Nineteen Thirty Six to Nineteen Forty Nine,");
println!("a period in which I had many duties that I did not neglect, and many other interests as a learner and teacher that often absorbed me.");
println!("The delay was, of course, also increased by the outbreak of war in Nineteen Thirty Nine, by the end of which year the tale had not yet reached the end of Book One.");
println!("In spite of the darkness of the next five years I found that the story could not now be wholly abandoned, and I plodded on, mostly by night, till I stood by Balin's tomb in Moria.");
println!("There I halted for a long while.");
println!("It was almost a year later when I went on and so came to Lothlórien and the Great River late in 1941.");
println!("In the next year I wrote the first drafts of the matter that now stands as Book Three,");
println!("and the beginnings of chapters One and Three of Book Five;");
println!("and there as the beacons flared in Anórien and Théoden came to Harrowdale I stopped.");
println!("Foresight had failed and there was no time for thought.");
println!("It was during 1944 that, leaving the loose ends and perplexities of a war which it was my task to conduct, or at least to report, I forced myself to tackle the journey of Frodo to Mordor.");
println!("These chapters, eventually to become Book Four, were written and sent out as a serial to my son, Christopher, then in South Africa with the RAF.");
println!("Nonetheless it took another five years before the tale was brought to its present end;");
println!("in that time I changed my house, my chair, and my college, and the days though less dark were no less laborious.");
println!("Then when the 'end' had at last been reached the whole story had to be revised, and indeed largely re-written backwards.");
println!("And it had to be typed, and re-typed:");
println!("by me;");
println!("the cost of professional typing by the ten-fingered was beyond my means.");
println!("The Lord of the Rings has been read by many people since it finally appeared in print;");
println!("and I should like to say something here with reference to the many opinions or guesses that I have received or have read concerning the motives and meaning of the tale.");
println!("The prime motive was the desire of a tale-teller to try his hand at a really long story that would hold the attention of readers,");
println!("amuse them, delight them, and at times maybe excite them or deeply move them.");
println!("As a guide I had only my own feelings for what is appealing or moving, and for many the guide was inevitably often at fault.");
println!("Some who have read the book, or at any rate have reviewed it, have found it boring, absurd, or contemptible;");
println!("and I have no cause to complain, since I have similar opinions of their works, or of the kinds of writing that they evidently prefer.");
println!("But even from the points of view of many who have enjoyed my story there is much that fails to please.");
println!("It is perhaps not possible in a long tale to please everybody at all points, nor to displease everybody at the same points;");
println!("for I find from the letters that I have received that the passages or chapters that are to some a blemish are all by others specially approved.");
println!("The most critical reader of all, myself, now finds many defects, minor and major,");
println!("but being fortunately under no obligation either to review the book or to write it again, he will pass over these in silence,");
println!("except one that has been noted by others:");
println!("the book is too short.");
println!("As for any inner meaning or 'message', it has in the intention of the author none.");
println!("It is neither allegorical nor topical.");
println!("As the story grew it put down roots (into the past) and threw out unexpected branches:");
println!("but its main theme was settled from the outset by the inevitable choice of the Ring as the link between it and The Hobbit.");
println!("The crucial chapter, 'The Shadow of the Past', is one of the oldest parts of the tale.");
println!("It was written long before the foreshadow of Nineteen Thirty Nine had yet become a threat of inevitable disaster,");
println!("and from that point the story would have developed along essentially the same lines, if that disaster had been averted.");
println!("Its sources are things long before in mind, or in some cases already written,");
println!("and little or nothing in it was modified by the war that began in Nineteen Thirty Nine or its sequels.");
println!("The real war does not resemble the legendary war in its process or its conclusion.");
println!("If it had inspired or directed the development of the legend, then certainly the Ring would have been seized and used against Sauron;");
println!("he would not have been annihilated but enslaved, and Barad-dûr would not have been destroyed but occupied.");
println!("Saruman, failing to get possession of the Ring,");
println!("would in the confusion and treacheries of the time have found in Mordor the missing links in his own researches into Ring-lore,");
println!("and before long he would have made a Great Ring of his own with which to challenge the self-styled Ruler of Middle-earth.");
println!("In that conflict both sides would have held hobbits in hatred and contempt:");
println!("they would not long have survived even as slaves.");
println!("Other arrangements could be devised according to the tastes or views of those who like allegory or topical reference.");
println!("But I cordially dislike allegory in all its manifestations, and always have done so since I grew old and wary enough to detect its presence.");
println!("I much prefer history, true or feigned, with its varied applicability to the thought and experience of readers.");
println!("I think that many confuse 'applicability' with 'allegory';");
println!("but the one resides in the freedom of the reader, and the other in the purposed domination of the author.");
println!("An author cannot of course remain wholly unaffected by his experience,");
println!("but the ways in which a story-germ uses the soil of experience are extremely complex,");
println!("and attempts to define the process are at best guesses from evidence that is inadequate and ambiguous.");
println!("It is also false, though naturally attractive, when the lives of an author and critic have overlapped,");
println!("to suppose that the movements of thought or the events of times common to both were necessarily the most powerful influences.");
println!("One has indeed personally to come under the shadow of war to feel fully its oppression;");
println!("but as the years go by it seems now often forgotten that to be caught in youth by Nineteen Fourteen was no less hideous an experience than to be involved in Nineteen Thirty Nine and the following years.");
println!("By Nineteen Eighteen all but one of my close friends were dead.");
println!("Or to take a less grievous matter:");
println!("it has been supposed by some that 'The Scouring of the Shire' reflects the situation in England at the time when I was finishing my tale.");
println!("It does not.");
println!("It is an essential part of the plot, foreseen from the outset, though in the event modified by the character of Saruman as developed in the story without,");
println!("need I say, any allegorical significance or contemporary political reference whatsoever.");
println!("It has indeed some basis in experience, though slender (for the economic situation was entirely different),");
println!("and much further back.");
println!("The country in which I lived in childhood was being shabbily destroyed before I was ten,");
println!("in days when motor-cars were rare objects (I had never seen one) and men were still building suburban railways.");
println!("Recently I saw in a paper a picture of the last decrepitude of the once thriving corn-mill beside its pool that long ago seemed to me so important.");
println!("I never liked the looks of the Young miller, but his father, the Old miller, had a black beard, and he was not named Sandyman.");
println!("The Lord of the Rings is now issued in a new edition, and the opportunity has been taken of revising it.");
println!("A number of errors and inconsistencies that still remained in the text have been corrected,");
println!("and an attempt has been made to provide information on a few points which attentive readers have raised.");
println!("I have considered all their comments and enquiries, and if some seem to have been passed over that may be because I have failed to keep my notes in order;");
println!("but many enquiries could only be answered by additional appendices,");
println!("or indeed by the production of an accessory volume containing much of the material that I did not include in the original edition,");
println!("in particular more detailed linguistic information.");
println!("In the meantime this edition offers this Foreword, an addition to the Prologue, some notes, and an index of the names of persons and places.");
println!("This index is in intention complete in items but not in references, since for the present purpose it has been necessary to reduce its bulk.");
println!("A complete index, making full use of the material prepared for me by Mrs. N. Smith, belongs rather to the accessory volume.");
println!("----------------------------------------------");
println!("{}", _prologue);
println!("This book is largely concerned with Hobbits, and from its pages a reader may discover much of their character and a little of their history.");
println!("Further information will also be found in the selection from the Red Book of Westmarch that has already been published, under the title of The Hobbit.");
println!("That story was derived from the earlier chapters of the Red Book, composed by Bilbo himself,");
println!("the first Hobbit to become famous in the world at large, and called by him There and Back Again,");
println!("since they told of his journey into the East and his return:");
println!("an adventure which later involved all the Hobbits in the great events of that Age that are here related.");
println!("Many, however, may wish to know more about this remarkable people from the outset, while some may not possess the earlier book.");
println!("For such readers a few notes on the more important points are here collected from Hobbit-lore, and the first adventure is briefly recalled.");
println!("Hobbits are an unobtrusive but very ancient people, more numerous formerly than they are today;");
println!("for they love peace and quiet and good tilled earth:");
println!("a well-ordered and well-farmed countryside was their favorite haunt.");
println!("They do not and did not understand or like machines more complicated than a forge-bellows,");
println!("a water-mill, or a hand-loom, though they were skillful with tools.");
println!("Even in ancient days they were, as a rule, shy of 'the Big Folk',");
println!("as they call us, and now they avoid us with dismay and are becoming hard to find.");
println!("They are quick of hearing and sharp-eyed, and though they are inclined to be fat and do not hurry unnecessarily,");
println!("they are nonetheless nimble and deft in their movements.");
println!("They possessed from the first the art of disappearing swiftly and silently,");
println!("when large folk whom they do not wish to meet come blundering by;");
println!("and this an they have developed until to Men it may seem magical.");
println!("But Hobbits have never, in fact, studied magic of any kind,");
println!("and their elusiveness is due solely to a professional skill that heredity and practice,");
println!("and a close friendship with the earth, have rendered inimitable by bigger and clumsier races.");
println!("For they are a little people, smaller than Dwarves:");
println!("less tout and stocky, that is, even when they are not actually much shorter.");
println!("Their height is variable, ranging between two and four feet of our measure.");
println!("They seldom now reach three feet;");
println!("but they hive dwindled, they say, and in ancient days they were taller.");
println!("According to the Red Book, Bandobras Took (Bullroarer),");
println!("son of Isengrim the Second, was four foot five and able to ride a horse.");
println!("He was surpassed in all Hobbit records only by two famous characters of old;");
println!("but that curious matter is dealt with in this book.");
println!("As for the Hobbits of the Shire, with whom these tales are concerned, in the days of their peace and prosperity they were a merry folk.");
println!("They dressed in bright colours, being notably fond of yellow and green;");
println!("but they seldom wore shoes, since their feet had tough leathery soles and were clad in a thick curling hair,");
println!("much like the hair of their heads, which was commonly brown.");
println!("Thus, the only craft little practised among them was shoe-making;");
println!("but they had long and skillful fingers and could make many other useful and comely things.");
println!("Their faces were as a rule good-natured rather than beautiful, broad, bright-eyed,");
println!("red-cheeked, with mouths apt to laughter, and to eating and drinking.");
println!("And laugh they did, and eat, and drink,");
println!("often and heartily, being fond of simple jests at all times,");
println!("and of six meals a day (when they could get them).");
println!("They were hospitable and delighted in parties, and in presents, which they gave away freely and eagerly accepted.");
println!("It is plain indeed that in spite of later estrangement Hobbits are relatives of ours:");
println!("far nearer to us than Elves, or even than Dwarves.");
println!("Of old they spoke the languages of Men, after their own fashion, and liked and disliked much the same things as Men did.");
println!("But what exactly our relationship is can no longer be discovered.");
println!("The beginning of Hobbits lies far back in the Elder Days that are now lost and forgotten.");
println!("Only the Elves still preserve any records of that vanished time, and their traditions are concerned almost entirely with their own history,");
println!("in which Men appear seldom and Hobbits are not mentioned at all.");
println!("Yet it is clear that Hobbits had, in fact, lived quietly in Middle-earth for many long years before other folk became even aware of them.");
println!("And the world being after all full of strange creatures beyond count,");
println!("these little people seemed of very little importance.");
println!("But in the days of Bilbo, and of Frodo his heir, they suddenly became, by no wish of their own,");
println!("both important and renowned, and troubled the counsels of the Wise and the Great.");
println!("Those days, the Third Age of Middle-earth, are now long past, and the shape of all lands has been changed;");
println!("but the regions in which Hobbits then lived were doubtless the same as those in which they still linger:");
println!("the North-West of the Old World, east of the Sea.");
println!("Of their original home the Hobbits in Bilbo's time preserved no knowledge.");
println!("A love of learning (other than genealogical lore) was far from general among them,");
println!("but there remained still a few in the older families who studied their own books,");
println!("and even gathered reports of old times and distant lands from Elves, Dwarves, and Men.");
println!("Their own records began only after the settlement of the Shire, and their most ancient legends hardly looked further back than their Wandering Days.");
println!("It is clear, nonetheless, from these legends, and from the evidence of their peculiar words and customs,");
println!("that like many other folk Hobbits had in the distant past moved westward.");
println!("Their earliest tales seem to glimpse a time when they dwelt in the upper vales of Anduin,");
println!("between the eaves of Greenwood the Great and the Misty Mountains.");
println!("Why they later undertook the hard and perilous crossing of the mountains into Eriador is no longer certain.");
println!("Their own accounts speak of the multiplying of Men in the land, and of a shadow that fell on the forest, so that it became darkened and its new name was Mirkwood.");
println!("Before the crossing of the mountains the Hobbits had already become divided into three somewhat different breeds:");
println!("Harfoots, Stoors, and Fallohides.");
println!("The Harfoots were browner of skin, smaller, and shorter, and they were beardless and bootless;");
println!("their hands and feet were neat and nimble;");
println!("and they preferred highlands and hillsides.");
println!("The Stoors were broader, heavier in build;");
println!("their feet and hands were larger, and they preferred flat lands and riversides.");
println!("The Fallohides were fairer of skin and also of hair, and they were taller and slimmer than the others;");
println!("they were lovers of trees and of woodlands.");
println!("The Harfoots had much to do with Dwarves in ancient times, and long lived in the foothills of the mountains.");
println!("They moved westward early, and roamed over Eriador as far as Weathertop while the others were still in the Wilderland.");
println!("They were the most normal and representative variety of Hobbit, and far the most numerous.");
println!("They were the most inclined to settle in one place, and longest preserved their ancestral habit of living in tunnels and holes.");
println!("The Stoors lingered long by the banks of the Great River Anduin, and were less shy of Men.");
println!("They came west after the Harfoots and followed the course of the Loudwater southwards;");
println!("and there many of them long dwelt between Tharbad and the borders of Dunland before they moved north again.");
println!("The Fallohides, the least numerous, were a northerly branch.");
println!("They were more friendly with Elves than the other Hobbits were,");
println!("and had more skill in language and song than in handicrafts;");
println!("and of old they preferred hunting to tilling.");
println!("They crossed the mountains north of Rivendell and came down the River Hoarwell.");
println!("In Eriador they soon mingled with the other kinds that had preceded them,");
println!("but being somewhat bolder and more adventurous,");
println!("they were often found as leaders or chieftains among clans of Harfoots or Stoors.");
println!("Even in Bilbo's time the strong Fallohidish strain could still be noted among the greater families,");
println!("such as the Tooks and the Masters of Buckland.");
println!("In the westlands of Eriador, between the Misty Mountains and the Mountains of Lune, the Hobbits found both Men and Elves.");
println!("Indeed, a remnant still dwelt there of the Dúnedain,");
println!("the kings of Men that came over the Sea out of Westernesse;");
println!("but they were dwindling fast and the lands of their North Kingdom were falling far and wide into waste.");
println!("There was room and to spare for incomers, and ere long the Hobbits began to settle in ordered communities.");
println!("Most of their earlier settlements had long disappeared and been forgotten in Bilbo's time;");
println!("but one of the first to become important still endured, though reduced in size;");
println!("this was at Bree and in the Chetwood that lay round about, some forty miles east of the Shire.");
println!("It was in these early days, doubtless,");
println!("that the Hobbits learned their letters and began to write after the manner of the Dúnedain,");
println!("who had in their turn long before learned the art from the Elves.");
println!("And in those days also they forgot whatever languages they had used before,");
println!("and spoke ever after the Common Speech, the Westron as it was named,");
println!("that was current through all the lands of the kings from Arnor to Gondor,");
println!("and about all the coasts of the Sea from Belfalas to Lune.");
println!("Yet they kept a few words of their own, as well as their own names of months and days,");
println!("and a great store of personal names out of the past.");
println!("About this time legend among the Hobbits first becomes history with a reckoning of years.");
println!("For it was in the one thousand six hundred and first year of the Third Age that the Fallohide brothers, Marcho and Blanco, set out from Bree;");
println!("and having obtained permission from the high king at Fornost,");
println!("they crossed the brown river Baranduin with a great following of Hobbits.");
println!("They passed over the Bridge of Stonebows, that had been built in the days of the power of the North Kingdom,");
println!("and they took ail the land beyond to dwell in, between the river and the Far Downs.");
println!("All that was demanded of them was that they should keep the Great Bridge in repair,");
println!("and all other bridges and roads, speed the king's messengers, and acknowledge his lordship.");
println!("Thus began the Shire-reckoning,");
println!("for the year of the crossing of the Brandywine (as the Hobbits turned the name) became Year One of the Shire,");
println!("and all later dates were reckoned from it.");
println!("At once the western Hobbits fell in love with their new land, and they remained there,");
println!("and soon passed once more out of the history of Men and of Elves.");
println!("While there was still a king they were in name his subjects, but they were, in fact,");
println!("ruled by their own chieftains and meddled not at all with events in the world outside.");
println!("To the last battle at Fornost with the Witch-lord of Angmar they sent some bowmen to the aid of the king,");
println!("or so they maintained, though no tales of Men record it.");
println!("But in that war the North Kingdom ended;");
println!("and then the Hobbits took the land for their own,");
println!("and they chose from their own chiefs a Thain to hold the authority of the king that was gone.");
println!("There for a thousand years they were little troubled by wars,");
println!("and they prospered and multiplied after the Dark Plague (Shire Reckoning Thirty Seven) until the disaster of the Long Winter and the famine that followed it.");
println!("Many thousands then perished,");
println!("but the Days of Dearth (One Thousand One Hundred Fifty Eight to One Thousand One Hundred Sixty) were at the time of this tale long past and the Hobbits had again become accustomed to plenty.");
println!("The land was rich and kindly, and though it had long been deserted when they entered it,");
println!("it had before been well tilled, and there the king had once had many farms, cornlands, vineyards, and woods.");
println!("Forty leagues it stretched from the Far Downs to the Brandywine Bridge,");
println!("and fifty from the northern moors to the marshes in the south.");
println!("The Hobbits named it the Shire, as the region of the authority of their Thain,");
println!("and a district of well-ordered business;");
println!("and there in that pleasant comer of the world they applied their well-ordered business of living,");
println!("and they heeded less and less the world outside where dark things moved,");
println!("until they came to think that peace and plenty were the rule in Middle-earth and the right of all sensible folk.");
println!("They forgot or ignored what little they had ever known of the Guardians,");
println!("and of the labours of those that made possible the long peace of the Shire.");
println!("They were, in fact, sheltered, but they had ceased to remember it.");
println!("At no time had Hobbits of any kind been warlike,");
println!("and they had never fought among themselves.");
println!("In olden days they had, of course,");
println!("been often obliged to fight to maintain themselves in a hard world;");
println!("but in Bilbo's time that was very ancient history.");
println!("The last battle, before this story opens,");
println!("and indeed the only one that had ever been fought within the borders of the Shire,");
println!("was beyond living memory:");
println!("the Battle of Greenfields, Shire Reckoning One Thousand One Hundred Forty Seven, in which Bandobras Took routed an invasion of Orcs.");
println!("Even the weathers had grown milder,");
println!("and the wolves that had once come ravening out of the North in bitter white winters were now only a grandfather's tale.");
println!("So, though there was still some store of weapons in the Shire, these were used mostly as trophies,");
println!("hanging above hearths or on walls, or gathered into the museum at Michel Delving.");
println!("The Mathom-house it was called;");
println!("for anything that Hobbits had no immediate use for,");
println!("but were unwilling to throw away, they called a mathom.");
println!("Their dwellings were apt to become rather crowded with mathoms,");
println!("and many of the presents that passed from hand to hand were of that son.");
println!("Nonetheless, ease and peace had left this people still curiously tough.");
println!("They were, if it came to it, difficult to daunt or to kill;");
println!("and they were, perhaps, so unwearyingly fond of good things not least because they could,");
println!("when put to it, do without them, and could survive rough handling by grief,");
println!("foe, or weather in a way that astonished those who did not know them well and looked no further than their bellies and their well-fed faces.");
println!("Though slow to quarrel, and for sport killing nothing that lived,");
println!("they were doughty at bay, and at need could still handle arms.");
println!("They shot well with the bow, for they were keen-eyed and sure at the mark.");
println!("Not only with bows and arrows.");
println!("If any Hobbit stooped for a stone,");
println!("it was well to get quickly under cover,");
println!("as all trespassing beasts knew very well.");
println!("All Hobbits had originally lived in holes in the ground, or so they believed,");
println!("and in such dwellings they still felt most at home;");
println!("but in the course of time they had been obliged to adopt other forms of abode.");
println!("Actually in the Shire in Bilbo's days it was, as a rule,");
println!("only the richest and the poorest Hobbits that maintained the old custom.");
println!("The poorest went on living in burrows of the most primitive kind, mere holes indeed, with only one window or none;");
println!("while the well-to-do still constructed more luxurious versions of the simple diggings of old.");
println!("But suitable sites for these large and ramifying tunnels (or smials as they called them) were not everywhere to be found;");
println!("and in the flats and the low-lying districts the Hobbits,");
println!("as they multiplied, began to build above ground.");
println!("Indeed, even in the hilly regions and the older villages,");
println!("such as Hobbiton or Tuckborough, or in the chief township of the Shire,");
println!("Michel Delving on the White Downs, there were now many houses of wood, brick, or stone.");
println!("These were specially favoured by millers, smiths, ropers, and cartwrights, and others of that sort;");
println!("for even when they had holes to live in.");
println!("Hobbits had long been accustomed to build sheds and workshops.");
println!("The habit of building farmhouses and barns was said to have begun among the inhabitants of the Marish down by the Brandywine.");
println!("The Hobbits of that quarter, the Eastfarthing,");
println!("were rather large and heavy-legged,");
println!("and they wore dwarf-boots in muddy weather.");
println!("But they were well known to be Stoors in a large part of their blood,");
println!("as indeed was shown by the down that many grew on their chins.");
println!("No Harfoot or Fallohide had any trace of a beard.");
println!("Indeed, the folk of the Marish, and of Buckland, east of the River, which they afterwards occupied,");
println!("came for the most part later into the Shire up from south-away;");
println!("and they still had many peculiar names and strange words not found elsewhere in the Shire.");
println!("It is probable that the craft of building, as many other crafts beside, was derived from the Dúnedain.");
println!("But the Hobbits may have learned it direct from the Elves, the teachers of Men in their youth.");
println!("For the Elves of the High Kindred had not yet forsaken Middle-earth,");
println!("and they dwelt still at that time at the Grey Havens away to the west,");
println!("and in other places within reach of the Shire.");
println!("Three Elf-towers of immemorial age were still to be seen on the Tower Hills beyond the western marches.");
println!("They shone far off in the moonlight.");
println!("The tallest was furthest away, standing alone upon a green mound.");
println!("The Hobbits of the Westfarthing said that one could see the Sea from the lop of that tower;");
println!("but no Hobbit had ever been known to climb it.");
println!("Indeed, few Hobbits had ever seen or sailed upon the Sea,");
println!("and fewer still had ever returned to report it.");
println!("Most Hobbits regarded even rivers and small boats with deep misgivings,");
println!("and not many of them could swim.");
println!("And as the days of the Shire lengthened they spoke less and less with the Elves,");
println!("and grew afraid of them, and distrustful of those that had dealings with them;");
println!("and the Sea became a word of fear among them, and a token of death,");
println!("and they turned their faces away from the hills in the west.");
println!("The craft of building may have come from Elves or Men, but the Hobbits used it in their own fashion.");
println!("They did not go in for towers.");
println!("Their houses were usually long, low, and comfortable.");
println!("The oldest kind were, indeed, no more than built imitations of smials,");
println!("thatched with dry grass or straw, or roofed with turves, and having walls somewhat bulged.");
println!("That stage, however, belonged to the early days of the Shire,");
println!("and hobbit-building had long since been altered, improved by devices,");
println!("learned from Dwarves, or discovered by themselves.");
println!("A preference for round windows, and even round doors, was the chief remaining peculiarity of hobbit-architecture.");
println!("The houses and the holes of Shire-hobbits were often large, and inhabited by large families.");
println!("(Bilbo and Frodo Baggins were as bachelors very exceptional, as they were also in many other ways, such as their friendship with the Elves.)");
println!("Sometimes, as in the case of the Tooks of Great Smials,");
println!("or the Brandybucks of Brandy Hall,");
println!("many generations of relatives lived in (comparative) peace together in one ancestral and many-tunneled mansion.");
println!("All Hobbits were, in any case, clannish and reckoned up their relationships with great care.");
println!("They drew long and elaborate family-trees with innumerable branches.");
println!("In dealing with Hobbits it is important to remember who is related to whom, and in what degree.");
println!("It would be impossible in this book to set out a family-tree that included even the more important members of the more important families at the time which these tales tell of.");
println!("The genealogical trees at the end of the Red Book of Westmarch are a small book in themselves,");
println!("and all but Hobbits would find them exceedingly dull.");
println!("Hobbits delighted in such things, if they were accurate:");
println!("they liked to have books filled with things that they already knew,");
println!("set out fair and square with no contradictions.");
println!("There is another astonishing thing about Hobbits of old that must be mentioned, an astonishing habit:");
println!("they imbibed or inhaled, through pipes of clay or wood,");
println!("the smoke of the burning leaves of a herb, which they called pipe-weed or leaf,");
println!("a variety probably of Nicotiana.");
println!("A great deal of mystery surrounds the origin of this peculiar custom,");
println!("or 'art' as the Hobbits preferred to call it.");
println!("All that could be discovered about it in antiquity was put together by Meriadoc Brandybuck (later Master of Buckland),");
println!("and since he and the tobacco of the Southfarthing play a part in the history that follows,");
println!("his remarks in the introduction to his Herblore of the Shire may be quoted.");
println!("This, he says, is the one art that we can certainly claim to be our own invention.");
println!("When Hobbits first began to smoke is not known,");
println!("all the legends and family histories take it for granted;");
println!("for ages folk in the Shire smoked various herbs, some fouler, some sweeter.");
println!("But all accounts agree that Tobold Hornblower of Longbottom in the Southfarthing first grew the true pipe-weed in his gardens in the days of Isengrim the Second,");
println!("about the year One Thousand Seventy of Shire-reckoning.");
println!("The best home-grown still comes from that district,");
println!("especially the varieties now known as Longbottom Leaf, Old Toby, and Southern Star.");
println!("How Old Toby came by the plant is not recorded, for to his dying day he would not tell.");
println!("He knew much about herbs, but he was no traveller.");
println!("It is said that in his youth he went often to Bree,");
println!("though he certainly never went further from the Shire than that.");
println!("It is thus quite possible that he learned of this plant in Bree, where now, at any rate,");
println!("it grows well on the south slopes of the hill.");
println!("The Bree-hobbits claim to have been the first actual smokers of the pipe-weed.");
println!("They claim, of course, to have done everything before the people of the Shire,");
println!("whom they refer to as 'colonists';");
println!("but in this case their claim is, I think, likely to be true.");
println!("And certainly it was from Bree that the art of smoking the genuine weed spread in the recent centuries among Dwarves and such other folk,");
println!("Rangers, Wizards, or wanderers, as still passed to and fro through that ancient road-meeting.");
println!("The home and centre of the an is thus to be found in the old inn of Bree,");
println!("The Prancing Pony, that has been kept by the family of Butterbur from time beyond record.");
println!("All the same,");
println!("observations that I have made on my own many journeys south have convinced me that the weed itself is not native to our parts of the world,");
println!("but came northward from the lower Anduin, whither it was, I suspect,");
println!("originally brought over Sea by the Men of Westernesse.");
println!("It grows abundantly in Gondor, and there is richer and larger than in the North,");
println!("where it is never found wild, and flourishes only in warm sheltered places like Longbottom.");
println!("The Men of Gondor call it sweet galenas, and esteem it only for the fragrance of its flowers.");
println!("From that land it must have been carried up the Greenway during the long centuries between the coming of Elendil and our own day.");
println!("But even the Dúnedain of Gondor allow us this credit:");
println!("Hobbits first put it into pipes.");
println!("Not even the Wizards first thought of that before we did.");
println!("Though one Wizard that I knew took up the art long ago, and became as skillful in it as in all other things that he put his mind to.");
println!("The Shire was divided into four quarters, the Farthings already referred to.");
println!("North, South, East, and West;");
println!("and these again each into a number of folk lands,");
println!("which still bore the names of some of the old leading families,");
println!("although by the time of this history these names were no longer found only in their proper folk lands.");
println!("Nearly all Tooks still lived in the Took land,");
println!("but that was not true of many other families,");
println!("such as the Bagginses or the Boffins.");
println!("Outside the Farthings were the East and West Marches:");
println!("the Buckland (see beginning of Chapter Five, Book One);");
println!("and the Westmarch added to the Shire in Shire Reckoning One Thousand Four Hundred Sixty Two.");
println!("The Shire at this time had hardly any 'government'.");
println!("Families for the most part managed their own affairs.");
println!("Growing food and eating it occupied most of their time.");
println!("In other matters they were, as a rule, generous and not greedy,");
println!("but contented and moderate, so that estates, farms, workshops,");
println!("and small trades tended to remain unchanged for generations.");
println!("There remained, of course, the ancient tradition concerning the high king at Fornost,");
println!("or Norbury as they called it, away north of the Shire.");
println!("But there had been no king for nearly a thousand years,");
println!("and even the ruins of Kings' Norbury were covered with grass.");
println!("Yet the Hobbits still said of wild folk and wicked things (such as trolls) that they had not heard of the king.");
println!("For they attributed to the king of old all their essential laws;");
println!("and usually they kept the laws of free will,");
println!("because they were The Rules (as they said),");
println!("both ancient and just.");
println!("It is true that the Took family had long been pre-eminent;");
println!("for the office of Thain had passed to them (from the Oldbucks) some centuries before,");
println!("and the chief Took had borne that title ever since.");
println!("The Thain was the master of the Shire-moot,");
println!("and captain of the Shire-muster and the Hobbitry-in-arms,");
println!("but as muster and moot were only held in times of emergency,");
println!("which no longer occurred,");
println!("the Thainship had ceased to be more than a nominal dignity.");
println!("The Took family was still, indeed, accorded a special respect,");
println!("for it remained both numerous and exceedingly wealthy,");
println!("and was liable to produce in every generation strong characters of peculiar habits and even adventurous temperament.");
println!("The latter qualities, however, were now rather tolerated (in the rich) than generally approved.");
println!("The custom endured, nonetheless, of referring to the head of the family as The Took, and of adding to his name, if required, a number:");
println!("such as Isengrim the Second, for instance.");
println!("The only real official in the Shire at this date was the Mayor of Michel Delving (or of the Shire),");
println!("who was elected every seven years at the Free Fair on the White Downs at the Lithe,");
println!("that is at Midsummer.");
println!("As mayor almost his only duty was to preside at banquets,");
println!("given on the Shire-holidays, which occurred at frequent intervals.");
println!("But the offices of Postmaster and First Sherriff were attached to the mayoralty,");
println!("so that he managed both the Messenger Service and the Watch.");
println!("These were the only Shire-services,");
println!("and the Messengers were the most numerous,");
println!("and much the busier of the two.");
println!("By no means all Hobbits were lettered,");
println!("but those who were wrote constantly to all their friends (and a selection of their relations) who lived further off than an afternoon's walk.");
println!("The Sherriffs was the name that the Hobbits gave to their police,");
println!("or the nearest equivalent that they possessed.");
println!("They had, of course, no uniforms (such things being quite unknown),");
println!("only a feather in their caps;");
println!("and they were in practice rather haywards than policemen,");
println!("more concerned with the strayings of beasts than of people.");
println!("There were in all the Shire only twelve of them,");
println!("three in each Farthing,");
println!("for Inside Work.");
println!("A rather larger body,");
println!("varying at need, was employed to 'beat the bounds',");
println!("and to see that Outsiders of any kind, great or small, did not make themselves a nuisance.");
println!("At the time when this story begins the Bounders, as they were called, had been greatly increased.");
println!("There were many reports and complaints of strange persons and creatures prowling about the borders,");
println!("or over them:");
println!("the first sign that all was not quite as it should be,");
println!("and always had been except in tales and legends of long ago.");
println!("Few heeded the sign, and not even Bilbo yet had any notion of what it portended.");
println!("Sixty years had passed since he set out on his memorable journey,");
println!("and he was old even for Hobbits,");
println!("who reached a hundred as often as not;");
println!("but much evidently still remained of the considerable wealth that he had brought back.");
println!("How much or how little he revealed to no one,");
println!("not even to Frodo his favorite 'nephew'.");
println!("And he still kept secret the ring that he had found.");
println!("As is told in The Hobbit,");
println!("there came one day to Bilbo's door the great Wizard, Gandalf the Grey,");
println!("and thirteen dwarves with him:");
println!("none other, indeed, than Thorin Oakenshield, descendant of kings, and his twelve companions in exile.");

println!("With them he set out, to his own lasting astonishment, on a morning of April,");
println!("it being then the year 1341 Shire-reckoning, on a quest of great treasure,");
println!("the dwarf-hoards of the Kings under the Mountain, beneath Erebor in Dale,");
println!("far off in the East.");
println!("The quest was successful, and the Dragon that guarded the hoard was destroyed.");
println!("Yet, though before all was won the Battle of Five Armies was fought,");
println!("and Thorin was slain, and many deeds of renown were done,");
println!("the matter would scarcely have concerned later history,");
println!("or earned more than a note in the long annals of the Third Age,");
println!("but for an 'accident' by the way.");
println!("The party was assailed by Orcs in a high pass of the Misty Mountains as they went towards Wilderland;");
println!("and so it happened that Bilbo was lost for a while in the black orc-mines deep under the mountains,");
println!("and there, as he groped in vain in the dark,");
println!("he put his hand on a ring,");
println!("lying on the floor of a tunnel.");
println!("He put it in his pocket.");
println!("It seemed then like mere luck.");
println!("Trying to find his way out.");
println!("Bilbo went on down to the roots of the mountains,");
println!("until he could go no further.");
println!("At the bottom of the tunnel lay a cold lake far from the light,");
println!("and on an island of rock in the water lived Gollum.");
println!("He was a loathsome little creature:");
println!("he paddled a small boat with his large flat feet,");

println!("peering with pale luminous eyes and catching blind fish with his long fingers,");
println!("and eating them raw.");
println!("He ate any living thing, even orcs, if he could catch it and strangle it without a struggle.");
println!("He possessed a secret treasure that had come to him long ages ago,");
println!("when he still lived in the light:");
println!("a ring of gold that made its wearer invisible.");
println!("It was the one thing he loved, his 'precious',");
println!("and he talked to it,");
println!("even when it was not with him.");
println!("For he kept it hidden safe in a hole on his island,");
println!("except when he was hunting or spying on the orcs of the mines.");















/*
Maybe he would have attacked Bilbo at once, if the ring had been on him when they met; but it was not, and the hobbit held in his hand an Elvish knife, which served him as a sword. So to gain time Gollum challenged Bilbo to the Riddle-game, saying that if he asked a riddle which Bilbo could not guess, then he would kill him and eat him; but if Bilbo defeated him, then he would do as Bilbo wished: he would lead him to a way out of the tunnels.
Since he was lost in the dark without hope, and could neither go on nor back. Bilbo accepted the challenge; and they asked one another many riddles. In the end Bilbo won the game, more by luck (as it seemed) than by wits; for he was stumped at last for a riddle to ask, and cried out, as his hand came upon the ring he lad picked up and forgotten: What haw I got in my pocket? This Gollum failed to answer, though he demanded three guesses.
The Authorities, it is true, differ whether this last question was a mere 'question' and not a 'riddle' according to the strict rules of the Game; but all agree that, after accepting it and trying to guess the answer, Gollum was bound by his promise. And Bilbo pressed him to keep his word; for the thought came to him that this slimy creature might prove false, even though such promises were held sacred, and of old all but the wickedest things feared to break them. But after ages alone in the dark Gollum's heart was black, and treachery was in it. He slipped away, and returned to the island, of which Bilbo knew nothing, not far off in the dark water. There, he thought, lay his ring. He was hungry now, and angry, and once his 'precious' was with him he would not fear any weapon at all.
But the ring was not on the island; he had lost it, it was gone. His screech sent a shiver down Bilbo's back, though he did not yet understand what had happened. But Gollum had at last leaped to a guess, too late. What has it got in its pocketses? he cried. The light in his eyes was like a green flame as he sped back to murder the hobbit and recover his 'precious'. Just in time Bilbo saw his peril, and he fled blindly up the passage away from the water; and once more he was saved by his luck. For just as he ran he put his hand in his pocket, and the ring slipped quietly on to his finger. So it was that Gollum passed him without seeing him, and went to guard the way out, lest the 'thief' should escape. Warily Bilbo followed him, as he went along, cursing, and talking to himself about his 'precious'; from which talk at last even Bilbo guessed the truth, and hope came to him in the darkness: he himself had found the marvellous ring and a chance of escape from the orcs and from Gollum.
At length they came to a halt before an unseen opening that led to the lower gates of the mines, on the eastward side of the mountains.
There Gollum crouched at bay, smelling and listening;
and Bilbo was tempted to slay him with his sword.
But pity stayed him, and though he kept the ring, in which his only hope lay,
he would not use it to help him kill the wretched creature at a disadvantage.
In the end, gathering his courage, he leaped over Gollum in the dark,
and fled away down the passage, pursued by his enemy's cries of hate and despair:
Thief, thief! Baggins! We hates it for ever!
*/


//println!("\n");

/*
println!("Chinese Version:");
println!("J.R.R.托尔金 - 指环王。 (1/4)");
println!("-----------------------------------------------");
println!("指环王");
println!("经过");
println!("J·R·R·托尔金");
println!("第 1 部分：魔戒远征队");
println!("第二部分：两座塔");
println!("第三部分：王者归来");
println!("包含索引和完整附录");
println!("天空下精灵王的三枚戒指，");
println!("七个矮人领主在他们的石头大厅里，");
println!("九个注定要死的凡人，");
println!("一张献给坐在黑暗王座上的黑魔王，");
println!("在暗影所在的魔多之地。");
println!("一环统治他们所有人，一环找到他们，");
println!("一枚戒指将他们全部带入并在黑暗中束缚他们，");
println!("在暗影所在的魔多之地。");
println!("内容");
println!("前言");
println!("序幕");
println!("1.关于霍比特人");
println!("2. 关于管道杂草");
println!("3. 夏尔的秩序");
println!("4. 关于戒指的发现");
println!("关于夏尔记录的注释");
println!("戒指的团契");
println!("第一册");
println!("第一章 期待已久的聚会");
println!("第二章：过去的阴影");
println!("第三章 三是公司");
println!("第四章：通往蘑菇的捷径");
println!("第五章 阴谋败露");
println!("第六章：古老的森林");
println!("第七章：在汤姆·庞巴迪尔的家里");
println!("第八章：巴罗丘陵上的雾气");
println!("第九章 跃跃小马的标志");
println!("第十章：行者");
println!("第十一章 黑暗中的一把刀");
println!("第十二章 飞往福特");
println!("第二册：");
println!("第一章：多次会议");
println!("第二章：埃尔隆德会议");
println!("第三章：指环南下");
println!("第四章 黑暗之旅");
println!("第五章：卡扎杜姆之桥");
println!("第六章：洛斯罗立安");
println!("第七章：凯兰崔尔之镜");
println!("第八章：告别罗瑞恩");
println!("第九章 大河");
println!("第十章 团契的破裂");
println!("两座塔楼");
println!("第三册：");
println!("第一章 波罗米尔的离开");
println!("第二章：洛汗骑士");
println!("第三章：乌鲁克海");
println!("第四章：树须");
println!("第五章：白骑士");
println!("第六章：金殿之王");
println!("第七章：圣盔谷");
println!("第八章：艾辛格之路");
println!("第九章：废品与废品");
println!("第十章：萨鲁曼的声音");
println!("第十一章：帕兰提尔");
println!("第四册：");
println!("第一章：驯服斯麦戈");
println!("第二章：沼泽之行");
println!("第三章：黑门关闭");
println!("第四章 药草炖兔");
println!("第五章：西窗");
println!("第六章：禁池");
println!("第七章：十字路口之旅");
println!("第八章：西里斯·昂戈尔 的阶梯");
println!("第九章：尸罗的巢穴");
println!("第十章：山姆怀斯大师的选择");
println!("王者归来");
println!("第五本书：");
println!("第一章：米那斯提力斯");
println!("第二章：灰色公司的消亡");
println!("第三章：洛汗集结");
println!("第四章：围攻刚铎");
println!("第五章：洛希尔人的骑行");
println!("第六章：佩兰诺平原之战");
println!("第七章：德内索尔的柴堆");
println!("第八章：治愈之家");
println!("第九章：最后的辩论");
println!("第十章：黑门开启");
println!("第六册：");
println!("第一章：奇力斯乌戈尔之塔");
println!("第二章：暗影之地");
println!("第三章：末日火山");
println!("第四章：科马伦原野");
println!("第五章：管家与国王");
println!("第六章：多次离别");
println!("第七章：归途");
println!("第八章：夏尔的扫荡");
println!("第九章：灰色天堂");
*/
























println!("Exit?");
let _exit_input = io::stdin().read_line(&mut exit);
}
