use std::io;
fn main() {
let mut Exit = String::new();
//Exit = "";

println!("J. R. R. Tolkien - Zoti i unazave. (1/4)");
println! ("---------------------------------------------- -");
println!("ZOTI I unazave");
println!("nga");
println!("J. R. R. TOLKIEN");
println! ("Pjesa e Parë: Shoqëria e Unazës");
println! ("Pjesa e Dytë: Dy Kullat");
println! ("Pjesa e tretë: Kthimi i mbretit");
println!("E plotësuar me indeks dhe shtojca të plota");
println!("Tre unaza për mbretërit Elven nën qiell");
println!("Shtatë për zotërinjtë xhuxh në sallat e tyre prej guri");
println! ("Nëntë për burrat e vdekshëm të dënuar të vdesin,");
println!("Një për Zotin e Errët në fronin e tij të errët");
println!("Në Tokën e Mordorit ku shtrihen Hijet.");
println!("Një unazë për t'i sunduar të gjithë,");
println!("Një unazë për t'i gjetur");
println!("Një Unazë për t'i sjellë të gjitha dhe në errësirë t'i lidhë");
println!("Në Tokën e Mordorit ku shtrihen Hijet.");
println!("PERMBAJTJA");
println!("PARATHËNIE");
println!("PROLOG");
println!("1. Në lidhje me Hobbitët");
println!("2. Lidhur me gypat e barërave të këqija");
println!("3. E Rendit te Shire");
println!("4. Nga Gjetja e Unazës");
println!("Shënim mbi të dhënat Shire");
println!("SHOQËRIA E UNAZËS");
println! ("Libri i parë:");
println!("Kapitulli 1 Një festë e pritur prej kohësh");
println!("Kapitulli 2 Hija e së kaluarës");
println!("Kapitulli 3 është kompani");
println!("Kapitulli 4 Një prerje e shkurtër për kërpudhat");
println! ("Kapitulli 5 Një komplot i demaskuar");
println! ("Kapitulli 6 Pylli i Vjetër");
println! ("Kapitulli 7 Në shtëpinë e Tom Bombadil");
println! ("Kapitulli 8 Mjegulla në Barrow-Downs");
println! ("Kapitulli 9 Në shenjën e kalit të vogël");
println!("Kapitulli 10 Strider");
println!("Kapitulli 11 Një thikë në errësirë");
println! ("Kapitulli 12 Fluturimi për në Ford");
println!("Libri i dyte:");
println! ("Kapitulli 1 Shumë Takime");
println!("Kapitulli 2 Këshilli i Elrondit");
println! ("Kapitulli 3 Unaza shkon në jug");
println! ("Kapitulli 4 Një udhëtim në errësirë");
println!("Kapitulli 5 Ura e Khazad-dûm");
println! ("Kapitulli 6 Lothlórien");
println!("Kapitulli 7 Pasqyra e Galadrielit");
println!("Kapitulli 8 Lamtumire Lórien");
println! ("Kapitulli 9 Lumi i Madh");
println! ("Kapitulli 10 Thyerja e Bashkësisë");
println!("DY KULLAT");
println!("Libri Tre:");
println!("Kapitulli 1 Largimi i Boromir");
println! ("Kapitulli 2 Kalorësit e Rohanit");
println!("Kapitulli 3 Uruk-Hai");
println!("Kapitulli 4 Mjekër Pema");
println! ("Kapitulli 5 Kalorësi i Bardhë");
println!("Kapitulli 6 Mbreti i Sallës së Artë");
println! ("Kapitulli 7 Helm's Deep");
println!("Kapitulli 8 Rruga drejt Isengardit");
println!("Kapitulli 9 Flotsam dhe Jetsam");
println!("Kapitulli 10 Zëri i Sarumanit");
println!("Kapitulli 11 Palantir");
println!("Libri i katërt:");
println!("Kapitulli 1 Zbutja e Sméagol");
println!("Kapitulli 2 Kalimi i kënetave");
println!("Kapitulli 3 Porta e Zezë është e Mbyllur");
println! ("Kapitulli 4 i barishteve dhe lepurit të zier");
println! ("Kapitulli 5 Dritarja në Perëndim");
println!("Kapitulli 6 Pishina e Ndaluar");
println! ("Kapitulli 7 Udhëtim në udhëkryq");
println!("Kapitulli 8 Shkallët e Cirith Ungol");
println!("Kapitulli 9 Varri i Shelobit");
println!("Kapitulli 10 Zgjedhjet e Master Samwise");
println!("KTHIMI I MBRETIT");
println!("Libri i peste:");
println!("Kapitulli 1 Minas Tirith");
println! ("Kapitulli 2 Kalimi i Kompanisë Gri");
println! ("Kapitulli 3 The Monster of Rohan");
println!("Kapitulli 4 Rrethimi i Gondorit");
println!("Kapitulli 5 Udhëtimi i Rohirrim");
println!("Kapitulli 6 Beteja e Fushave Pelennor");
println!("Kapitulli 7 Pyre of Denethor");
println!("Kapitulli 8 Shtëpitë e Shërimit");
println!("Kapitulli 9 Debati i fundit");
println!("Kapitulli 10 Hapet Porta e Zezë");
println!("Libri i Gjashtë:");
println!("Kapitulli 1 Kulla e Cirith Ungol");
println! ("Kapitulli 2 Toka e hijes");
println! ("Kapitulli 3 Mount Doom");
println!("Kapitulli 4 Fusha e Cormallen");
println!("Kapitulli 5 Kujdestari dhe Mbreti");
println!("Kapitulli 6 Shumë ndarje");
println! ("Kapitulli 7 Lidhur në shtëpi");
println!("Kapitulli 8 Pastrimi i Shirit");
println! ("Kapitulli 9 The Grey Havens");
println!("SHTOJCA");
println!("NJË ANALI I MBRETIT DHE Sundimtarëve");
println!("Unë Mbretërit Numenorean");
println!("(I) Númenor");
println!("(II) Mbretëritë në mërgim");
println!("(III) Eriador, Arnor dhe Trashëgimtarët e Isildurit");
println! ("(IV) Gondor dhe trashëgimtarët e Anñrion");
println!("(V) Këtu vijon një pjesë e Përrallës së Aragorn dhe Arwen");
println!("II THE HOUSE OF EORL");
println!("FOLKRI I III DURINIT");
println!("Këtu vijon një nga shënimet e fundit në Librin e Kuq");
println!("B PERRALLA E VITIT (KRONOLOGJIA E VENDEVE PERENDIMORE)");
println!("Epoka e Dyte");
println!("Epoka e Trete");
println!("PEMËT FAMILJARE C");
println!("KALENDARET D");
println!("KALENDAR SHIRE PËR PËRDORIM NË TË GJITHA VITET");
println!("KALENDARET");
println!("SHKRIMI DHE DREJTSHKRIMI");
println!("I shqiptimi i fjaleve dhe i emrave");
println!("Shkrimi II");
println!("F");
println!("Unë gjuhët dhe popujt e epokës së tretë");
println!("II Mbi Përkthimin");
println!("INDEKSET");
println!("I Këngë dhe Vargje");
println!("II Persona, Bisha dhe Përbindësha");
println!("Vendet III");
println!("IV Gjërat");
println!("----------------------------------------------");
println!("PARATHËNIE");
println!("Kjo përrallë u rrit në tregim, derisa u bë histori e Luftës së Madhe të Unazës dhe përfshiu shumë pamje të historisë akoma më të lashtë që i parapriu.");
println!("Ai filloi menjëherë pasi u shkrua 'Hobbit' dhe para botimit të tij në 1937;");
println!("por nuk vazhdova me këtë vazhdim, sepse doja së pari të plotësoja dhe të rregulloja mitologjinë dhe legjendat e Ditëve të Pleqve, që atëherë kishin marrë formë prej disa vitesh.");
println!("Dëshiroja ta bëja këtë për kënaqësinë time dhe kisha pak shpresë se njerëzit e tjerë do të ishin të interesuar për këtë punë,");
println!("veçanërisht pasi ishte kryesisht gjuhësor në frymëzim dhe filloi për të siguruar sfondin e nevojshëm të 'historisë' për gjuhët elvish.");
println!("Kur ata, këshillat dhe mendimet e të cilëve kërkova, korrigjuan pak shpresë në pa shpresë, u ktheva në vazhdim");
println! ("inkurajuar nga kërkesat e lexuesve për më shumë informacion në lidhje me hobbitët dhe aventurat e tyre.");
println!("Por historia u tërhoq në mënyrë të papërmbajtshme drejt botës së vjetër dhe u bë një rrëfim, si të thuash, i fundit dhe i vdekjes së saj para se të tregohej fillimi dhe mesi i saj.");
println!("Procesi kishte filluar në shkrimin e The Hobbit, në të cilin tashmë kishte disa referenca për çështjen më të vjetër:");
println!("Elrond, Gondolin, High-Elf-të dhe orkët, si dhe pamjet që kishin dalë pa u shfaqur nga gjërat më të larta ose më të thella ose më të errëta se sipërfaqja e tij:");
println!("Durin, Moria, Gandalf, Necromancer, Unaza.");
println!("Zbulimi i rëndësisë së këtyre pamjeve dhe i lidhjes së tyre me historitë e lashta zbuloi Epokën e Tretë dhe kulmin e saj në Luftën e Unazës.");
println!("Ata që kishin kërkuar më shumë informacion për hobbitët më në fund e morën atë, por u duhej të prisnin shumë;");
println!("sepse kompozimi i 'The Lord of the Rings' vazhdoi me intervale gjatë viteve 1936 deri në 1949,");
println!("një periudhë në të cilën kisha shumë detyra që nuk i lashë pas dore dhe shumë interesa të tjera si nxënës dhe mësues që shpesh më përthithën.");
println!("Vonesat, natyrisht, u rritën edhe nga shpërthimi i luftës në vitin 1939, në fund të të cilit përralla nuk kishte arritur ende në fund të Librit të Parë.");
println!("Megjithë errësirën e pesë viteve të ardhshme, kuptova se historia tani nuk mund të braktisej plotësisht, dhe vazhdova, kryesisht natën, derisa qëndrova pranë varrit të Balinit në Moria.");
println!("Atje ndalova për një kohë të gjatë.");
println!("Ishte pothuajse një vit më vonë kur vazhdova dhe kështu erdha në Lothlórien dhe në lumin e Madh në fund të 1941.");
println!("Në vitin e ardhshëm shkrova draftet e para të çështjes që tani qëndron si Libri i Tretë,");
println!("dhe fillimet e kapitujve I dhe III te librit pese;");
println!("dhe aty teksa fenerët u ndezën në Anórien dhe Théoden erdhën në Harrowdale, unë ndalova.");
println!("Parashikimi kishte dështuar dhe nuk kishte kohë për të menduar.");
println!("Ka qenë gjatë vitit 1944 që, duke lënë përfundimet e lira dhe hutimet e një lufte që ishte detyra ime ta drejtoja, ose të paktën të raportoja, e detyrova veten të merrem me udhëtimin e Frodos në Mordor.");
println!("Këta kapituj, që përfundimisht do të bëhen Libri i Katërt, u shkruan dhe iu dërguan si serial djalit tim, Christopher, atëherë në Afrikën e Jugut me RAF.");
println!("Megjithatë u deshën edhe pesë vjet para se përralla të arrinte në fundin e saj aktual;");
println!("në atë kohë unë ndryshova shtëpinë time, karrigen time dhe kolegjin tim, dhe ditët edhe pse më pak të errëta nuk ishin më pak të mundimshme.");
println!("Atëherë kur më në fund u arrit 'fundi', e gjithë historia duhej të rishikohej dhe në të vërtetë të rishkruhej në masë të madhe mbrapsht.");
println!("Dhe duhej të shtypej dhe të rishkruhej:");
println!("nga unë;");
println!("kostoja e shtypjes profesionale me dhjetë gishta ishte përtej mundësive të mia.");
println!("Zoti i unazave është lexuar nga shumë njerëz që kur u shfaq më në fund në shtyp;");
println!("dhe unë do të doja të them diçka këtu duke iu referuar shumë mendimeve ose supozimeve që kam marrë ose kam lexuar në lidhje me motivet dhe kuptimin e përrallës.");
println!("Motivi kryesor ishte dëshira e një tregimtari për të provuar dorën e tij në një histori vërtet të gjatë që do të tërhiqte vëmendjen e lexuesve");
println!("zbavitini, kënaqini dhe ndonjëherë mund t'i ngacmoni ose t'i prekni thellë.");
println!("Si udhërrëfyes unë kisha vetëm ndjenjat e mia për atë që është tërheqëse ose lëvizëse, dhe për shumë njerëz udhërrëfyesi ishte në mënyrë të pashmangshme shpesh në faj.");
println!("Disa që e kanë lexuar librin, ose në çdo rast e kanë rishikuar, e kanë parë të mërzitshëm, absurd ose të përçmuar;");
println!("dhe nuk kam pse të ankohem, pasi kam mendime të ngjashme për veprat e tyre, ose për llojet e shkrimeve që ata me sa duket preferojnë.");
println!("Por edhe nga këndvështrimi i shumë atyre që e kanë shijuar historinë time ka shumë gjëra që nuk mund të kënaqin.");
println!("Ndoshta nuk është e mundur në një përrallë të gjatë t'i kënaqësh të gjithë në të gjitha pikat, as të mos i kënaqësh të gjithë në të njëjtat pika;");
println!("sepse nga letrat që kam marrë zbuloj se pasazhet ose kapitujt që janë për disa të meta janë të gjitha të miratuara posaçërisht nga të tjerët.");
println!("Lexuesi më kritik nga të gjithë, unë, tani gjen shumë defekte, të vogla dhe të mëdha,");
println!("por fatmirësisht duke mos pasur asnjë detyrim as ta rishikojë librin, as ta shkruajë përsëri, ai do t'i kalojë këto në heshtje,");
println!("përveç një që është shënuar nga të tjerët:");
println!("libri është shumë i shkurtër.");
println!("Sa i përket çdo kuptimi ose 'mesazhi' të brendshëm, ai nuk ka në qëllimin e autorit asnjë.");
println!("Nuk eshte as alegorike dhe as aktuale.");
println!("Ndërsa historia u rrit, ajo hodhi rrënjët (në të kaluarën) dhe hodhi degë të papritura:");
println!("por tema e saj kryesore u zgjidh që në fillim nga zgjedhja e pashmangshme e Unazës si lidhje midis saj dhe Hobbit.");
println!("Kapitulli vendimtar 'Hija e së kaluarës', është një nga pjesët më të vjetra të përrallës.");
println!("U shkrua shumë kohë përpara se parathënia e vitit 1939 të ishte bërë ende një kërcënim i fatkeqësisë së pashmangshme");
println!("dhe nga ajo pikë historia do të ishte zhvilluar në thelb në të njëjtat linja, nëse ajo fatkeqësi do të ishte shmangur.");
println!("Burimet e tij janë gjëra shumë më parë në mendje, ose në disa raste tashmë të shkruara,");
println!("dhe pak ose aspak në të u modifikua nga lufta që filloi në 1939 ose nga vazhdimet e saj.");
println!("Lufta e vërtetë nuk i ngjan luftës legjendare në procesin e saj apo përfundimin e saj.");
println!("Nëse do të kishte frymëzuar ose drejtuar zhvillimin e legjendës, atëherë me siguri Unaza do të ishte kapur dhe përdorur kundër Sauronit;");
println!("ai nuk do të ishte asgjësuar, por robëruar, dhe Barad-dûr nuk do të ishte shkatërruar, por pushtuar.");
println!("Saruman, duke dështuar për të zotëruar Unazën,");
println!("a do të kishte gjetur në konfuzionin dhe tradhtitë e kohës tek Mordor hallkat që mungojnë në kërkimet e tij në Ring-lore,");
println!("dhe pa kaluar shumë kohë ai do të kishte bërë një Unazë të Madhe të tijën me të cilën do të sfidonte Sundimtarin e vetëquajtur të Tokës së Mesme.");
println!("Në atë konflikt të dyja palët do t'i kishin mbajtur hobbit në urrejtje dhe përbuzje:");
println!("ata nuk do të kishin mbijetuar gjatë edhe si skllevër.");
println!("Aranzhime të tjera mund të krijohen sipas shijeve ose pikëpamjeve të atyre që pëlqejnë alegorinë ose referencën aktuale.");
println!("Por mua nuk më pëlqen përzemërsisht alegoria në të gjitha manifestimet e saj, dhe gjithmonë e kam bërë këtë që kur jam plakur dhe mjaft i kujdesshëm për të zbuluar praninë e saj.");
println!("Unë e preferoj shumë historinë, të vërtetë apo të shtirur, me zbatueshmërinë e saj të larmishme në mendimin dhe përvojën e lexuesve.");
println!("Unë mendoj se shumë ngatërrojnë 'zbatueshmërinë' me 'alegorinë';");
println!("por njëra qëndron në lirinë e lexuesit dhe tjetra në dominimin e synuar të autorit.");
println!("Një autor sigurisht që nuk mund të mbetet tërësisht i pandikuar nga përvoja e tij,");
println!("por mënyrat në të cilat një mikrob histori përdor tokën e përvojës janë jashtëzakonisht komplekse,");
println!("dhe përpjekjet për të përcaktuar procesin janë supozime më të mira nga provat që janë të pamjaftueshme dhe të paqarta.");
println!("Është gjithashtu e rreme, ndonëse natyrshëm tërheqëse, kur jeta e një autori dhe kritiku janë mbivendosur");
println!("të supozojmë se lëvizjet e mendimit ose ngjarjet e kohërave të përbashkëta për të dyja ishin domosdoshmërisht ndikimet më të fuqishme.");
println!("Njeriu me te vertete personalisht duhet te bjere nen hijen e luftes per te ndjere plotesisht shtypjen e saj;");
println!("por me kalimin e viteve, duket se tani shpesh harrohet se të kapeshe në rini deri në vitin 1914 nuk ishte një përvojë më pak e frikshme sesa të përfshiheshe në 1939 dhe vitet në vijim.");
println!("Në vitin 1918, të gjithë përveç njërit nga miqtë e mi të ngushtë kishin vdekur.");
println!("Ose për të marrë një çështje më pak të rëndë:");
println!("nga disa është supozuar se 'The Scouring of the Shire' pasqyron situatën në Angli në kohën kur unë po mbaroja përrallën time.");
println!("Nuk ka.");
println!("Është një pjesë thelbësore e komplotit, e parashikuar që në fillim, edhe pse në rastin e modifikuar nga personazhi i Saruman siç është zhvilluar në tregim pa");
println!("duhet të them, çfarëdo rëndësie alegorike apo referencë politike bashkëkohore.");
println!("Me të vërtetë ka një bazë në përvojë, edhe pse e hollë (sepse situata ekonomike ishte krejtësisht e ndryshme)");
println!("dhe shumë më mbrapa.");
println!("Vendi në të cilin jetoja në fëmijëri po shkatërrohej në mënyrë të shkretë para se të isha dhjetë vjeç,");
println!("në ditët kur makinat motorike ishin objekte të rralla (nuk e kisha parë kurrë) dhe burrat ende ndërtonin hekurudha periferike.");
println!("Kohët e fundit pashë në një gazetë një fotografi të varfërisë së fundit të mullirit të misrit dikur të lulëzuar pranë pishinës së tij që shumë kohë më parë më dukej kaq e rëndësishme.");
println!("Kurrë nuk më pëlqeu pamja e mullisit të ri, por babai i tij, mullixhiu i vjetër, kishte mjekër të zezë dhe nuk quhej Sandyman.");
println!("Zoti i unazave tani është botuar në një botim të ri dhe është shfrytëzuar mundësia për ta rishikuar.");
println!("Një numër gabimesh dhe mospërputhjesh që kanë mbetur ende në tekst janë korrigjuar,");
println!("dhe është bërë një përpjekje për të dhënë informacion për disa pika që lexuesit e vëmendshëm i kanë ngritur.");
println!("Kam shqyrtuar të gjitha komentet dhe pyetjet e tyre, dhe nëse disa duket se janë kaluar, kjo mund të jetë për shkak se nuk kam mbajtur shënimet e mia në rregull;");
println!("por shumë pyetjeve mund të përgjigjen vetëm me shtojca shtesë,");
println!("ose në të vërtetë nga prodhimi i një vëllimi shtesë që përmban shumë nga materiali që unë nuk e kam përfshirë në botimin origjinal,");
println!("në veçanti informacion më të detajuar gjuhësor.");
println!("Ndërkohë ky botim ofron këtë Parathënie, një shtesë në Prolog, disa shënime dhe një tregues të emrave të personave dhe vendeve.");
println!("Ky indeks është në qëllim i plotë në artikuj, por jo në referenca, pasi për qëllimin aktual ka qenë e nevojshme të zvogëlohet pjesa më e madhe e tij.");
println!("Një indeks i plotë, duke shfrytëzuar plotësisht materialin e përgatitur për mua nga zonja N. Smith, i përket më tepër vëllimit shtesë.");
println!("----------------------------------------------");
println!("PROLOGUE");
println!("This book is largely concerned with Hobbits, and from its pages a reader may discover much of their character and a little of their history.");
println!("Further information will also be found in the selection from the Red Book of Westmarch that has already been published, under the title of The Hobbit.");
println!("That story was derived from the earlier chapters of the Red Book, composed by Bilbo himself,");
println!("the first Hobbit to become famous in the world at large, and called by him There and Back Again,");
println!("since they told of his journey into the East and his return:");
println!("an adventure which later involved all the Hobbits in the great events of that Age that are here related.");
println!("Many, however, may wish to know more about this remarkable people from the outset, while some may not possess the earlier book.");
println!("For such readers a few notes on the more important points are here collected from Hobbit-lore, and the first adventure is briefly recalled.");
println!("Hobbits are an unobtrusive but very ancient people, more numerous formerly than they are today;");
println!("for they love peace and quiet and good tilled earth:");
println!("a well-ordered and well-farmed countryside was their favourite haunt.");
println!("They do not and did not understand or like machines more complicated than a forge-bellows,");
println!("a water-mill, or a hand-loom, though they were skillful with tools.");
println!("Even in ancient days they were, as a rule, shy of 'the Big Folk',");
println!("as they call us, and now they avoid us with dismay and are becoming hard to find.");
println!("They are quick of hearing and sharp-eyed, and though they are inclined to be fat and do not hurry unnecessarily,");
println!("they are nonetheless nimble and deft in their movements.");
println!("They possessed from the first the art of disappearing swiftly and silently,");
println!("when large folk whom they do not wish to meet come blundering by;");
println!("and this an they have developed until to Men it may seem magical.");
println!("But Hobbits have never, in fact, studied magic of any kind,");
println!("and their elusiveness is due solely to a professional skill that heredity and practice,");
println!("and a close friendship with the earth, have rendered inimitable by bigger and clumsier races.");
println!("For they are a little people, smaller than Dwarves:");
println!("less tout and stocky, that is, even when they are not actually much shorter.");
println!("Their height is variable, ranging between two and four feet of our measure.");
println!("They seldom now reach three feet;");
println!("but they hive dwindled, they say, and in ancient days they were taller.");
println!("According to the Red Book, Bandobras Took (Bullroarer),");
println!("son of Isengrim the Second, was four foot five and able to ride a horse.");
println!("He was surpassed in all Hobbit records only by two famous characters of old;");
println!("but that curious matter is dealt with in this book.");
println!("As for the Hobbits of the Shire, with whom these tales are concerned, in the days of their peace and prosperity they were a merry folk.");
println!("They dressed in bright colours, being notably fond of yellow and green;");
println!("but they seldom wore shoes, since their feet had tough leathery soles and were clad in a thick curling hair,");
println!("much like the hair of their heads, which was commonly brown.");
println!("Thus, the only craft little practised among them was shoe-making;");
println!("but they had long and skilful fingers and could make many other useful and comely things.");
println!("Their faces were as a rule good-natured rather than beautiful, broad, bright-eyed,");
println!("red-cheeked, with mouths apt to laughter, and to eating and drinking.");
println!("And laugh they did, and eat, and drink,");
println!("often and heartily, being fond of simple jests at all times,");
println!("and of six meals a day (when they could get them).");
println!("They were hospitable and delighted in parties, and in presents, which they gave away freely and eagerly accepted.");
println!("It is plain indeed that in spite of later estrangement Hobbits are relatives of ours:");
println!("far nearer to us than Elves, or even than Dwarves.");
println!("Of old they spoke the languages of Men, after their own fashion, and liked and disliked much the same things as Men did.");
println!("But what exactly our relationship is can no longer be discovered.");
println!("The beginning of Hobbits lies far back in the Elder Days that are now lost and forgotten.");
println!("Only the Elves still preserve any records of that vanished time, and their traditions are concerned almost entirely with their own history,");
println!("in which Men appear seldom and Hobbits are not mentioned at all.");
println!("Yet it is clear that Hobbits had, in fact, lived quietly in Middle-earth for many long years before other folk became even aware of them.");
println!("And the world being after all full of strange creatures beyond count,");
println!("these little people seemed of very little importance.");
println!("But in the days of Bilbo, and of Frodo his heir, they suddenly became, by no wish of their own,");
println!("both important and renowned, and troubled the counsels of the Wise and the Great.");
println!("Those days, the Third Age of Middle-earth, are now long past, and the shape of all lands has been changed;");
println!("but the regions in which Hobbits then lived were doubtless the same as those in which they still linger:");
println!("the North-West of the Old World, east of the Sea.");
println!("Of their original home the Hobbits in Bilbo's time preserved no knowledge.");
println!("A love of learning (other than genealogical lore) was far from general among them,");
println!("but there remained still a few in the older families who studied their own books,");
println!("and even gathered reports of old times and distant lands from Elves, Dwarves, and Men.");
println!("Their own records began only after the settlement of the Shire, and their most ancient legends hardly looked further back than their Wandering Days.");
println!("It is clear, nonetheless, from these legends, and from the evidence of their peculiar words and customs,");
println!("that like many other folk Hobbits had in the distant past moved westward.");
println!("Their earliest tales seem to glimpse a time when they dwelt in the upper vales of Anduin,");
println!("between the eaves of Greenwood the Great and the Misty Mountains.");
println!("Why they later undertook the hard and perilous crossing of the mountains into Eriador is no longer certain.");
println!("Their own accounts speak of the multiplying of Men in the land, and of a shadow that fell on the forest, so that it became darkened and its new name was Mirkwood.");
println!("Before the crossing of the mountains the Hobbits had already become divided into three somewhat different breeds:");
println!("Harfoots, Stoors, and Fallohides.");
println!("The Harfoots were browner of skin, smaller, and shorter, and they were beardless and bootless;");
println!("their hands and feet were neat and nimble;");
println!("and they preferred highlands and hillsides.");
println!("The Stoors were broader, heavier in build;");
println!("their feet and hands were larger, and they preferred flat lands and riversides.");
println!("The Fallohides were fairer of skin and also of hair, and they were taller and slimmer than the others;");
println!("they were lovers of trees and of woodlands.");
println!("The Harfoots had much to do with Dwarves in ancient times, and long lived in the foothills of the mountains.");
println!("They moved westward early, and roamed over Eriador as far as Weathertop while the others were still in the Wilderland.");
println!("They were the most normal and representative variety of Hobbit, and far the most numerous.");
println!("They were the most inclined to settle in one place, and longest preserved their ancestral habit of living in tunnels and holes.");
println!("The Stoors lingered long by the banks of the Great River Anduin, and were less shy of Men.");
println!("They came west after the Harfoots and followed the course of the Loudwater southwards;");
println!("and there many of them long dwelt between Tharbad and the borders of Dunland before they moved north again.");
println!("The Fallohides, the least numerous, were a northerly branch.");
println!("They were more friendly with Elves than the other Hobbits were,");
println!("and had more skill in language and song than in handicrafts;");
println!("and of old they preferred hunting to tilling.");
println!("They crossed the mountains north of Rivendell and came down the River Hoarwell.");
println!("In Eriador they soon mingled with the other kinds that had preceded them,");
println!("but being somewhat bolder and more adventurous,");
println!("they were often found as leaders or chieftains among clans of Harfoots or Stoors.");
println!("Even in Bilbo's time the strong Fallohidish strain could still be noted among the greater families,");
println!("such as the Tooks and the Masters of Buckland.");
println!("In the westlands of Eriador, between the Misty Mountains and the Mountains of Lune, the Hobbits found both Men and Elves.");
println!("Indeed, a remnant still dwelt there of the Dúnedain,");
println!("the kings of Men that came over the Sea out of Westernesse;");
println!("but they were dwindling fast and the lands of their North Kingdom were falling far and wide into waste.");
println!("There was room and to spare for incomers, and ere long the Hobbits began to settle in ordered communities.");
println!("Most of their earlier settlements had long disappeared and been forgotten in Bilbo's time;");
println!("but one of the first to become important still endured, though reduced in size;");
println!("this was at Bree and in the Chetwood that lay round about, some forty miles east of the Shire.");
println!("It was in these early days, doubtless,");
println!("that the Hobbits learned their letters and began to write after the manner of the Dúnedain,");
println!("who had in their turn long before learned the art from the Elves.");
println!("And in those days also they forgot whatever languages they had used before,");
println!("and spoke ever after the Common Speech, the Westron as it was named,");
println!("that was current through all the lands of the kings from Arnor to Gondor,");
println!("and about all the coasts of the Sea from Belfalas to Lune.");
println!("Yet they kept a few words of their own, as well as their own names of months and days,");
println!("and a great store of personal names out of the past.");
println!("About this time legend among the Hobbits first becomes history with a reckoning of years.");
println!("For it was in the one thousand six hundred and first year of the Third Age that the Fallohide brothers, Marcho and Blanco, set out from Bree;");
println!("and having obtained permission from the high king at Fornost,");
println!("they crossed the brown river Baranduin with a great following of Hobbits.");
println!("They passed over the Bridge of Stonebows, that had been built in the days of the power of the North Kingdom,");
println!("and they took ail the land beyond to dwell in, between the river and the Far Downs.");
println!("All that was demanded of them was that they should keep the Great Bridge in repair,");
println!("and all other bridges and roads, speed the king's messengers, and acknowledge his lordship.");
println!("Thus began the Shire-reckoning,");
println!("for the year of the crossing of the Brandywine (as the Hobbits turned the name) became Year One of the Shire,");
println!("and all later dates were reckoned from it.");
println!("At once the western Hobbits fell in love with their new land, and they remained there,");
println!("and soon passed once more out of the history of Men and of Elves.");
println!("While there was still a king they were in name his subjects, but they were, in fact,");
println!("ruled by their own chieftains and meddled not at all with events in the world outside.");
println!("To the last battle at Fornost with the Witch-lord of Angmar they sent some bowmen to the aid of the king,");
println!("or so they maintained, though no tales of Men record it.");
println!("But in that war the North Kingdom ended;");
println!("and then the Hobbits took the land for their own,");
println!("and they chose from their own chiefs a Thain to hold the authority of the king that was gone.");
println!("There for a thousand years they were little troubled by wars,");
println!("and they prospered and multiplied after the Dark Plague (S.R. 37) until the disaster of the Long Winter and the famine that followed it.");
println!("Many thousands then perished,");
println!("but the Days of Dearth (1158-60) were at the time of this tale long past and the Hobbits had again become accustomed to plenty.");
println!("The land was rich and kindly, and though it had long been deserted when they entered it,");
println!("it had before been well tilled, and there the king had once had many farms, cornlands, vineyards, and woods.");
println!("Forty leagues it stretched from the Far Downs to the Brandywine Bridge,");
println!("and fifty from the northern moors to the marshes in the south.");
println!("The Hobbits named it the Shire, as the region of the authority of their Thain,");
println!("and a district of well-ordered business;");
println!("and there in that pleasant comer of the world they applied their well-ordered business of living,");
println!("and they heeded less and less the world outside where dark things moved,");
println!("until they came to think that peace and plenty were the rule in Middle-earth and the right of all sensible folk.");
println!("They forgot or ignored what little they had ever known of the Guardians,");
println!("and of the labours of those that made possible the long peace of the Shire.");
println!("They were, in fact, sheltered, but they had ceased to remember it.");
println!("At no time had Hobbits of any kind been warlike,");
println!("and they had never fought among themselves.");
println!("In olden days they had, of course,");
println!("been often obliged to fight to maintain themselves in a hard world;");
println!("but in Bilbo's time that was very ancient history.");
println!("The last battle, before this story opens,");
println!("and indeed the only one that had ever been fought within the borders of the Shire,");
println!("was beyond living memory:");
println!("the Battle of Greenfields, S.R. 1147, in which Bandobras Took routed an invasion of Orcs.");
println!("Even the weathers had grown milder,");
println!("and the wolves that had once come ravening out of the North in bitter white winters were now only a grandfather's tale.");
println!("So, though there was still some store of weapons in the Shire, these were used mostly as trophies,");
println!("hanging above hearths or on walls, or gathered into the museum at Michel Delving.");
println!("The Mathom-house it was called;");
println!("for anything that Hobbits had no immediate use for,");
println!("but were unwilling to throw away, they called a mathom.");
println!("Their dwellings were apt to become rather crowded with mathoms,");
println!("and many of the presents that passed from hand to hand were of that son.");
println!("Nonetheless, ease and peace had left this people still curiously tough.");
println!("They were, if it came to it, difficult to daunt or to kill;");
println!("and they were, perhaps, so unwearyingly fond of good things not least because they could,");
println!("when put to it, do without them, and could survive rough handling by grief,");
println!("foe, or weather in a way that astonished those who did not know them well and looked no further than their bellies and their well-fed faces.");
println!("Though slow to quarrel, and for sport killing nothing that lived,");
println!("they were doughty at bay, and at need could still handle arms.");
println!("They shot well with the bow, for they were keen-eyed and sure at the mark.");
println!("Not only with bows and arrows.");
println!("If any Hobbit stooped for a stone,");
println!("it was well to get quickly under cover,");
println!("as all trespassing beasts knew very well.");
println!("All Hobbits had originally lived in holes in the ground, or so they believed,");
println!("and in such dwellings they still felt most at home;");
println!("but in the course of time they had been obliged to adopt other forms of abode.");
println!("Actually in the Shire in Bilbo's days it was, as a rule,");
println!("only the richest and the poorest Hobbits that maintained the old custom.");
println!("The poorest went on living in burrows of the most primitive kind, mere holes indeed, with only one window or none;");
println!("while the well-to-do still constructed more luxurious versions of the simple diggings of old.");
println!("But suitable sites for these large and ramifying tunnels (or smials as they called them) were not everywhere to be found;");
println!("and in the flats and the low-lying districts the Hobbits,");
println!("as they multiplied, began to build above ground.");
println!("Indeed, even in the hilly regions and the older villages,");
println!("such as Hobbiton or Tuckborough, or in the chief township of the Shire,");
println!("Michel Delving on the White Downs, there were now many houses of wood, brick, or stone.");
println!("These were specially favoured by millers, smiths, ropers, and cartwrights, and others of that sort;");
println!("for even when they had holes to live in.");
println!("Hobbits had long been accustomed to build sheds and workshops.");
println!("The habit of building farmhouses and barns was said to have begun among the inhabitants of the Marish down by the Brandywine.");
println!("The Hobbits of that quarter, the Eastfarthing,");
println!("were rather large and heavy-legged,");
println!("and they wore dwarf-boots in muddy weather.");
println!("But they were well known to be Stoors in a large part of their blood,");
println!("as indeed was shown by the down that many grew on their chins.");
println!("No Harfoot or Fallohide had any trace of a beard.");
println!("Indeed, the folk of the Marish, and of Buckland, east of the River, which they afterwards occupied,");
println!("came for the most part later into the Shire up from south-away;");
println!("and they still had many peculiar names and strange words not found elsewhere in the Shire.");
println!("It is probable that the craft of building, as many other crafts beside, was derived from the Dúnedain.");
println!("But the Hobbits may have learned it direct from the Elves, the teachers of Men in their youth.");
println!("For the Elves of the High Kindred had not yet forsaken Middle-earth,");
println!("and they dwelt still at that time at the Grey Havens away to the west,");
println!("and in other places within reach of the Shire.");
println!("Three Elf-towers of immemorial age were still to be seen on the Tower Hills beyond the western marches.");
println!("They shone far off in the moonlight.");
println!("The tallest was furthest away, standing alone upon a green mound.");
println!("The Hobbits of the Westfarthing said that one could see the Sea from the lop of that tower;");
println!("but no Hobbit had ever been known to climb it.");
println!("Indeed, few Hobbits had ever seen or sailed upon the Sea,");
println!("and fewer still had ever returned to report it.");
println!("Most Hobbits regarded even rivers and small boats with deep misgivings,");
println!("and not many of them could swim.");
println!("And as the days of the Shire lengthened they spoke less and less with the Elves,");
println!("and grew afraid of them, and distrustful of those that had dealings with them;");
println!("and the Sea became a word of fear among them, and a token of death,");
println!("and they turned their faces away from the hills in the west.");
println!("The craft of building may have come from Elves or Men, but the Hobbits used it in their own fashion.");
println!("They did not go in for towers.");
println!("Their houses were usually long, low, and comfortable.");
println!("The oldest kind were, indeed, no more than built imitations of smials,");
println!("thatched with dry grass or straw, or roofed with turves, and having walls somewhat bulged.");
println!("That stage, however, belonged to the early days of the Shire,");
println!("and hobbit-building had long since been altered, improved by devices,");
println!("learned from Dwarves, or discovered by themselves.");
println!("A preference for round windows, and even round doors, was the chief remaining peculiarity of hobbit-architecture.");
println!("The houses and the holes of Shire-hobbits were often large, and inhabited by large families.");
println!("(Bilbo and Frodo Baggins were as bachelors very exceptional, as they were also in many other ways, such as their friendship with the Elves.)");
println!("Sometimes, as in the case of the Tooks of Great Smials,");
println!("or the Brandybucks of Brandy Hall,");
println!("many generations of relatives lived in (comparative) peace together in one ancestral and many-tunnelled mansion.");
println!("All Hobbits were, in any case, clannish and reckoned up their relationships with great care.");
println!("They drew long and elaborate family-trees with innumerable branches.");
println!("In dealing with Hobbits it is important to remember who is related to whom, and in what degree.");
println!("It would be impossible in this book to set out a family-tree that included even the more important members of the more important families at the time which these tales tell of.");
println!("The genealogical trees at the end of the Red Book of Westmarch are a small book in themselves,");
println!("and all but Hobbits would find them exceedingly dull.");
println!("Hobbits delighted in such things, if they were accurate:");
println!("they liked to have books filled with things that they already knew,");
println!("set out fair and square with no contradictions.");
println!("There is another astonishing thing about Hobbits of old that must be mentioned, an astonishing habit:");
println!("they imbibed or inhaled, through pipes of clay or wood,");
println!("the smoke of the burning leaves of a herb, which they called pipe-weed or leaf,");
println!("a variety probably of Nicotiana.");
println!("A great deal of mystery surrounds the origin of this peculiar custom,");
println!("or 'art' as the Hobbits preferred to call it.");
println!("All that could be discovered about it in antiquity was put together by Meriadoc Brandybuck (later Master of Buckland),");
println!("and since he and the tobacco of the Southfarthing play a part in the history that follows,");
println!("his remarks in the introduction to his Herblore of the Shire may be quoted.");
println!("This, he says, is the one art that we can certainly claim to be our own invention.");
println!("When Hobbits first began to smoke is not known,");
println!("all the legends and family histories take it for granted;");
println!("for ages folk in the Shire smoked various herbs, some fouler, some sweeter.");
println!("But all accounts agree that Tobold Hornblower of Longbottom in the Southfarthing first grew the true pipe-weed in his gardens in the days of Isengrim the Second,");
println!("about the year 1070 of Shire-reckoning.");
println!("The best home-grown still comes from that district,");
println!("especially the varieties now known as Longbottom Leaf, Old Toby, and Southern Star.");
println!("How Old Toby came by the plant is not recorded, for to his dying day he would not tell.");
println!("He knew much about herbs, but he was no traveller.");
println!("It is said that in his youth he went often to Bree,");
println!("though he certainly never went further from the Shire than that.");
println!("It is thus quite possible that he learned of this plant in Bree, where now, at any rate,");
println!("it grows well on the south slopes of the hill.");
println!("The Bree-hobbits claim to have been the first actual smokers of the pipe-weed.");
println!("They claim, of course, to have done everything before the people of the Shire,");
println!("whom they refer to as 'colonists';");
println!("but in this case their claim is, I think, likely to be true.");
println!("And certainly it was from Bree that the art of smoking the genuine weed spread in the recent centuries among Dwarves and such other folk,");
println!("Rangers, Wizards, or wanderers, as still passed to and fro through that ancient road-meeting.");
println!("The home and centre of the an is thus to be found in the old inn of Bree,");
println!("The Prancing Pony, that has been kept by the family of Butterbur from time beyond record.");
println!("All the same,");
println!("observations that I have made on my own many journeys south have convinced me that the weed itself is not native to our parts of the world,");
println!("but came northward from the lower Anduin, whither it was, I suspect,");
println!("originally brought over Sea by the Men of Westernesse.");
println!("It grows abundantly in Gondor, and there is richer and larger than in the North,");
println!("where it is never found wild, and flourishes only in warm sheltered places like Longbottom.");
println!("The Men of Gondor call it sweet galenas, and esteem it only for the fragrance of its flowers.");
println!("From that land it must have been carried up the Greenway during the long centuries between the coming of Elendil and our own day.");
println!("But even the Dúnedain of Gondor allow us this credit:");
println!("Hobbits first put it into pipes.");
println!("Not even the Wizards first thought of that before we did.");
println!("Though one Wizard that I knew took up the art long ago, and became as skillful in it as in all other things that he put his mind to.");
println!("The Shire was divided into four quarters, the Farthings already referred to.");
println!("North, South, East, and West;");
println!("and these again each into a number of folklands,");
println!("which still bore the names of some of the old leading families,");
println!("although by the time of this history these names were no longer found only in their proper folklands.");
println!("Nearly all Tooks still lived in the Tookland,");
println!("but that was not true of many other families,");
println!("such as the Bagginses or the Boffins.");
println!("Outside the Farthings were the East and West Marches:");
println!("the Buckland (see beginning of Chapter V, Book I);");
println!("and the Westmarch added to the Shire in S.R. 1462.");
println!("The Shire at this time had hardly any 'government'.");
println!("Families for the most part managed their own affairs.");
println!("Growing food and eating it occupied most of their time.");
println!("In other matters they were, as a rule, generous and not greedy,");
println!("but contented and moderate, so that estates, farms, workshops,");
println!("and small trades tended to remain unchanged for generations.");
println!("There remained, of course, the ancient tradition concerning the high king at Fornost,");
println!("or Norbury as they called it, away north of the Shire.");
println!("But there had been no king for nearly a thousand years,");
println!("and even the ruins of Kings' Norbury were covered with grass.");
println!("Yet the Hobbits still said of wild folk and wicked things (such as trolls) that they had not heard of the king.");
println!("For they attributed to the king of old all their essential laws;");
println!("and usually they kept the laws of free will,");
println!("because they were The Rules (as they said),");
println!("both ancient and just.");
println!("It is true that the Took family had long been pre-eminent;");
println!("for the office of Thain had passed to them (from the Oldbucks) some centuries before,");
println!("and the chief Took had borne that title ever since.");
println!("The Thain was the master of the Shire-moot,");
println!("and captain of the Shire-muster and the Hobbitry-in-arms,");
println!("but as muster and moot were only held in times of emergency,");
println!("which no longer occurred,");
println!("the Thainship had ceased to be more than a nominal dignity.");
println!("The Took family was still, indeed, accorded a special respect,");
println!("for it remained both numerous and exceedingly wealthy,");
println!("and was liable to produce in every generation strong characters of peculiar habits and even adventurous temperament.");
println!("The latter qualities, however, were now rather tolerated (in the rich) than generally approved.");
println!("The custom endured, nonetheless, of referring to the head of the family as The Took, and of adding to his name, if required, a number:");
println!("such as Isengrim the Second, for instance.");




























/*
The only real official in the Shire at this date was the Mayor of Michel Delving (or of the Shire), who was elected every seven years at the Free Fair on the White Downs at the Lithe, that is at Midsummer. As mayor almost his only duty was to preside at banquets, given on the Shire-holidays, which occurred at frequent intervals. But the offices of Postmaster and First Shirriff were attached to the mayoralty, so that he managed both the Messenger Service and the Watch. These were the only Shire-services, and the Messengers were the most numerous, and much the busier of the two. By no means all Hobbits were lettered, but those who were wrote constantly to all their friends (and a selection of their relations) who lived further off than an afternoon's walk.
The Shirriffs was the name that the Hobbits gave to their police, or the nearest equivalent that they possessed. They had, of course, no uniforms (such things being quite unknown), only a feather in their caps; and they were in practice rather haywards than policemen, more concerned with the strayings of beasts than of people. There were in all the Shire only twelve of them, three in each Farthing, for Inside Work. A rather larger body, varying at need, was employed to 'beat the bounds', and to see that Outsiders of any kind, great or small, did not make themselves a nuisance.
At the time when this story begins the Bounders, as they were called, had been greatly increased. There were many reports and complaints of strange persons and creatures prowling about the borders, or over them: the first sign that all was not quite as it should be, and always had been except in tales and legends of long ago. Few heeded the sign, and not even Bilbo yet had any notion of what it portended. Sixty years had passed since he set out on his memorable journey, and he was old even for Hobbits, who reached a hundred as often as not; but much evidently still remained of the considerable wealth that he had brought back. How much or how little he revealed to no one, not even to Frodo his favourite 'nephew'. And he still kept secret the ring that he bad found.
*/


//println!("\n");
/*
println!("Chinese Version:");
println!("J.R.R.托尔金 - 指环王。 (1/4)");
println!("-----------------------------------------------");
println!("指环王");
println!("经过");
println!("J·R·R·托尔金");
println!("第 1 部分：魔戒远征队");
println!("第二部分：两座塔");
println!("第三部分：王者归来");
println!("包含索引和完整附录");
println!("天空下精灵王的三枚戒指，");
println!("七个矮人领主在他们的石头大厅里，");
println!("九个注定要死的凡人，");
println!("一张献给坐在黑暗王座上的黑魔王，");
println!("在暗影所在的魔多之地。");
println!("一环统治他们所有人，一环找到他们，");
println!("一枚戒指将他们全部带入并在黑暗中束缚他们，");
println!("在暗影所在的魔多之地。");
println!("内容");
println!("前言");
println!("序幕");
println!("1.关于霍比特人");
println!("2. 关于管道杂草");
println!("3. 夏尔的秩序");
println!("4. 关于戒指的发现");
println!("关于夏尔记录的注释");
println!("戒指的团契");
println!("第一册");
println!("第一章 期待已久的聚会");
println!("第二章：过去的阴影");
println!("第三章 三是公司");
println!("第四章：通往蘑菇的捷径");
println!("第五章 阴谋败露");
println!("第六章：古老的森林");
println!("第七章：在汤姆·庞巴迪尔的家里");
println!("第八章：巴罗丘陵上的雾气");
println!("第九章 跃跃小马的标志");
println!("第十章：行者");
println!("第十一章 黑暗中的一把刀");
println!("第十二章 飞往福特");
println!("第二册：");
println!("第一章：多次会议");
println!("第二章：埃尔隆德会议");
println!("第三章：指环南下");
println!("第四章 黑暗之旅");
println!("第五章：卡扎杜姆之桥");
println!("第六章：洛斯罗立安");
println!("第七章：凯兰崔尔之镜");
println!("第八章：告别罗瑞恩");
println!("第九章 大河");
println!("第十章 团契的破裂");
println!("两座塔楼");
println!("第三册：");
println!("第一章 波罗米尔的离开");
println!("第二章：洛汗骑士");
println!("第三章：乌鲁克海");
println!("第四章：树须");
println!("第五章：白骑士");
println!("Chapter Six: The King of the Golden Hall");
println!("Chapter Seven: Helm's Deep");
println!("Chapter Eight: The Road to Isengard");
println!("Chapter Nine: Flotsam and Jetsam");
println!("Chapter Ten: The Voice of Saruman");
println!("Chapter Eleven: The Palantir");
println!("Book Four:");
println!("Chapter One: The Taming of Sméagol");
println!("Chapter Two: The Passage of the Marshes");
println!("Chapter Three: The Black Gate is Closed");
println!("Chapter Four: Of Herbs and Stewed Rabbit");
println!("Chapter Five: The Window on the West");
println!("Chapter Six: The Forbidden Pool");
println!("Chapter Seven: Journey to the Cross-roads");
println!("Chapter Eight: The Stairs of Cirith Ungol");
println!("Chapter Nine: Shelob's Lair");
println!("Chapter Ten: The Choices of Master Samwise");
println!("THE RETURN OF THE KING");
println!("Book Five:");
println!("Chapter 1 Minas Tirith");
println!("Chapter 2 The Passing of the Grey Company");
println!("Chapter 3 The Muster of Rohan");
println!("Chapter 4 The Siege of Gondor");
println!("Chapter 5 The Ride of the Rohirrim");
println!("Chapter 6 The Battle of the Pelennor Fields");
println!("Chapter 7 The Pyre of Denethor");
println!("Chapter 8 The Houses of Healing");
println!("Chapter 9 The Last Debate");
println!("Chapter 10 The Black Gate Opens");
println!("Book Six:");
println!("Chapter 1 The Tower of Cirith Ungol");
println!("Chapter 2 The Land of Shadow");
println!("Chapter 3 Mount Doom");
println!("Chapter 4 The Field of Cormallen");
println!("Chapter 5 The Steward and the King");
println!("Chapter 6 Many Partings");
println!("Chapter 7 Homeward Bound");
println!("Chapter 8 The Scouring of the Shire");
println!("Chapter 9 The Grey Havens");
*/
























println!("Exit?");
io::stdin().read_line(&mut Exit);
}
